import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,BarChart3,BedDouble,Bike,CheckCircle2,Cog,Download,Edit3,FileSpreadsheet,Package,PackagePlus,Power,Search,ShieldAlert,TrendingUp,UploadCloud,Wrench,X} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import * as XLSX from 'xlsx';
import type {Product,Ticket,TicketItem} from '../../types';
import {productMasterService,ProductCreateInput,ProductMasterChanges} from '../../services/productMasterService';
import {salesVolumeService,SalesVolumeRecord} from '../../services/salesVolumeService';
import {apiService} from '../../services/apiService';

type Props={currentUserRole:string;onChanged?:()=>void|Promise<void>};
type Draft={name:string;codeSku:string;description:string;model:string;brand:string;anvisaRegister:string;supplierName:string;manufacturerName:string;importerName:string;distributorName:string;countryOrigin:string;imageUrl:string};
type Period='90'|'365'|'all';
type IntelligenceRow={key:string;productId?:string;name:string;model:string;sku:string;brand:string;manufacturer:string;occurrences:number;critical:number;topDefect:string;topDefectCount:number;topReport:string;last:string;salesUnits:number;incidencePerThousand:number|null};
const empty:Draft={name:'',codeSku:'',description:'',model:'',brand:'Procirúrgica',anvisaRegister:'',supplierName:'',manufacturerName:'',importerName:'',distributorName:'',countryOrigin:'',imageUrl:''};
const canManage=(role:string)=>['SUPERADMIN','RESPONSAVEL_TECNICA','ADMIN_EMPRESA'].includes(role);
const canImportSales=(role:string)=>['SUPERADMIN','DIRETORIA','RESPONSAVEL_TECNICA','ADMIN_EMPRESA'].includes(role);
const COLORS=['#ef4444','#f59e0b','#eab308','#22c55e','#3b82f6','#8b5cf6','#64748b','#06b6d4'];
const normalize=(v?:string)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const compact=(v?:string)=>normalize(v).replace(/\s+/g,'');
const clean=(v?:string)=>String(v||'').replace(/\s+/g,' ').trim();
const money=(v?:number)=>v==null?'—':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const integer=(v:number)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:0});
const genericDefect=(v?:string)=>{const n=normalize(v);return !n||['reclamacao de produto','reclamacao produto','produto','outros','outro','nao classificado','sem classificacao','defeito de produto'].includes(n)};
const administrativeDefect=(v?:string)=>{const n=normalize(v);if(!n)return true;const exact=['cpf','cnpj','cpf ou cnpj','cpf cnpj','documento','documento do cliente','identificacao','identificacao do cliente','cadastro','cadastro do cliente','cliente','consumidor','pessoa fisica','pessoa juridica','razao social','nome fantasia','telefone','email','e mail','endereco','cep','lojista'];if(exact.includes(n))return true;if(/\b(cpf|cnpj|documento|identificacao|cadastro|razao social|nome fantasia|telefone|email|e mail|endereco|cep|lojista)\b/.test(n))return true;if(/^\d{11,14}$/.test(n.replace(/\s/g,'')))return true;return false};
const technicalDefect=(v?:string)=>!genericDefect(v)&&!administrativeDefect(v);
const defectFromTicket=(t:Ticket)=>{const structured=[t.classification,t.subcategory].map(clean).find(v=>technicalDefect(v));if(structured)return structured!;const text=normalize([t.description,t.classification,t.subcategory].filter(v=>v&&!administrativeDefect(String(v))).join(' '));const rules:[RegExp,string][]=[[/freio|travamento|trava|nao freia/,'Falha no sistema de freio'],[/motor|eletric|energia|nao liga|acionamento|controle|painel/,'Falha elétrica / motor'],[/quebr|fratur|trinc|romp|solda|estrutura/,'Quebra / falha estrutural'],[/roda|rodizio|pneu|eixo/,'Falha em roda / rodízio'],[/vazamento|vaza|liquido/,'Vazamento'],[/rasg|estof|revest|tecido|couro/,'Estofamento / revestimento danificado'],[/falt.*peca|ausente|nao veio|incomplet/,'Componente ausente / produto incompleto'],[/ruido|barulho|rangido/,'Ruído anormal'],[/montagem|montar|ajuste|desalinh|folg/,'Montagem / ajuste'],[/bateria|carregador|carga/,'Bateria / alimentação'],[/ferrug|oxid|pintura|acabamento|descasc/,'Acabamento / oxidação'],[/deform|amass|avaria|transporte|embalagem/,'Avaria / deformação'],[/costura|velcro|cinto|faixa/,'Falha em acessório / fixação']];for(const[re,label]of rules)if(re.test(text))return label;return'Defeito ainda não classificado'};
const reportSnippet=(t:Ticket)=>{const d=clean(t.description);return d?d.length>105?d.slice(0,102)+'…':d:'Sem relato técnico detalhado'};
const extractModel=(value?:string)=>{const s=clean(value).toUpperCase();const m=s.match(/\bPRO\s*\d+(?:\s*PLUS)?\b/);return m?compact(m[0]):''};
const productLabel=(name:string,model:string)=>{const n=clean(name)||'Produto não identificado',m=clean(model);return m&&!compact(n).includes(compact(m))?`${n} ${m}`:n};
const resolveProduct=(item:TicketItem,byId:Map<string,Product>,bySku:Map<string,Product>,byName:Map<string,Product>,byModel:Map<string,Product>)=>{if(item.productId&&byId.has(item.productId))return byId.get(item.productId);const sku=compact(item.sku);if(sku&&bySku.has(sku))return bySku.get(sku);const name=normalize(item.productName);if(name&&byName.has(name))return byName.get(name);const model=extractModel(`${item.productName||''} ${item.productModel||''}`);if(model&&byModel.has(model))return byModel.get(model);return undefined};
const normalizeHeader=(v:string)=>compact(v);
const pick=(row:Record<string,unknown>,keys:string[])=>{const entries=Object.entries(row);for(const key of keys){const target=normalizeHeader(key);const hit=entries.find(([k])=>normalizeHeader(k)===target);if(hit&&String(hit[1]??'').trim()!=='')return hit[1]}return''};
const excelDate=(v:unknown)=>{if(v==null||v==='')return'';if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const s=String(v).trim();const br=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(br)return`${br[3]}-${br[2].padStart(2,'0')}-${br[1].padStart(2,'0')}`;const iso=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return iso?`${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`:s};
const toNumber=(v:unknown)=>{if(typeof v==='number')return v;let s=String(v??'').trim().replace(/R\$/gi,'').replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};

export const ProductCatalogModule:React.FC<Props>=({currentUserRole,onChanged})=>{
 const [products,setProducts]=useState<Product[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[sales,setSales]=useState<SalesVolumeRecord[]>([]),[query,setQuery]=useState(''),[showInactive,setShowInactive]=useState(false),[editing,setEditing]=useState<Product|null>(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState<Draft>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState<'intelligence'|'catalog'|'sales'>('intelligence'),[period,setPeriod]=useState<Period>('365'),[intelQuery,setIntelQuery]=useState(''),[importInfo,setImportInfo]=useState('');
 const fileRef=useRef<HTMLInputElement|null>(null),allowed=canManage(currentUserRole),salesAllowed=canImportSales(currentUserRole);
 const load=async()=>{setError('');try{const[catalog,occurrences,salesRows]=await Promise.all([productMasterService.list(),apiService.getTickets(),salesVolumeService.list()]);setProducts(catalog);setTickets(occurrences);setSales(salesRows)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar produtos e indicadores.')}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>products.filter(p=>{if(!showInactive&&p.isActive===false)return false;const q=normalize(query);if(!q)return true;return[p.name,p.codeSku,p.model,p.brand,p.anvisaRegister,p.manufacturerName,p.supplierName].some(v=>normalize(v).includes(q))}),[products,query,showInactive]);
 const stats=useMemo(()=>({total:products.length,active:products.filter(p=>p.isActive!==false).length,noAnvisa:products.filter(p=>p.isActive!==false&&!p.anvisaRegister).length,noDescription:products.filter(p=>p.isActive!==false&&!p.description).length}),[products]);
 const intelligence=useMemo(()=>{
   const now=Date.now(),cutoff=period==='all'?0:now-Number(period)*86400000,cutoffIso=cutoff?new Date(cutoff).toISOString().slice(0,10):'';
   const byId=new Map(products.map(p=>[p.id,p])),bySku=new Map(products.filter(p=>p.codeSku).map(p=>[compact(p.codeSku),p])),byName=new Map(products.filter(p=>p.name).map(p=>[normalize(p.name),p])),byModel=new Map(products.filter(p=>p.model).map(p=>[compact(p.model),p]));
   const source=tickets.filter(t=>!cutoff||new Date(t.createdAt).getTime()>=cutoff),seen=new Set<string>();
   const records:{key:string;product?:Product;name:string;model:string;sku:string;brand:string;manufacturer:string;defect:string;report:string;critical:boolean;createdAt:string}[]=[];
   source.forEach(ticket=>ticket.items.forEach(item=>{const product=resolveProduct(item,byId,bySku,byName,byModel);const name=clean(product?.name||item.productName)||'Produto não identificado',model=clean(product?.model||item.productModel)||extractModel(item.productName),sku=clean(product?.codeSku||item.sku)||'',canonical=product?.id||`${normalize(name)}|${compact(model)}`,occurrenceKey=`${ticket.id}:${canonical}`;if(seen.has(occurrenceKey))return;seen.add(occurrenceKey);records.push({key:canonical,product,name,model,sku,brand:clean(product?.brand)||'',manufacturer:clean(product?.manufacturerName||item.manufacturerName)||'',defect:defectFromTicket(ticket),report:reportSnippet(ticket),critical:ticket.priority==='CRITICAL'||ticket.userRiskFlag||ticket.adverseEventFlag||ticket.damageFlag,createdAt:ticket.createdAt})}));
   const salesByProduct=new Map<string,number>();sales.filter(r=>period==='all'||!cutoffIso||r.periodEnd>=cutoffIso).forEach(r=>{if(r.productId)salesByProduct.set(r.productId,(salesByProduct.get(r.productId)||0)+r.unitsSold)});
   const groups=new Map<string,{key:string;productId?:string;name:string;model:string;sku:string;brand:string;manufacturer:string;occurrences:number;critical:number;defects:Map<string,number>;reports:Map<string,string>;last:string}>();
   records.forEach(r=>{const g=groups.get(r.key)||{key:r.key,productId:r.product?.id,name:r.name,model:r.model,sku:r.sku,brand:r.brand,manufacturer:r.manufacturer,occurrences:0,critical:0,defects:new Map<string,number>(),reports:new Map<string,string>(),last:r.createdAt};g.occurrences++;if(r.critical)g.critical++;g.defects.set(r.defect,(g.defects.get(r.defect)||0)+1);if(!g.reports.has(r.defect))g.reports.set(r.defect,r.report);if(new Date(r.createdAt)>new Date(g.last))g.last=r.createdAt;groups.set(r.key,g)});
   const modelRows:IntelligenceRow[]=[...groups.values()].map(g=>{const top=[...g.defects.entries()].sort((a,b)=>b[1]-a[1])[0],salesUnits=g.productId?(salesByProduct.get(g.productId)||0):0;return{key:g.key,productId:g.productId,name:g.name,model:g.model,sku:g.sku,brand:g.brand||'Procirúrgica',manufacturer:g.manufacturer,occurrences:g.occurrences,critical:g.critical,topDefect:top?.[0]||'Defeito ainda não classificado',topDefectCount:top?.[1]||0,topReport:g.reports.get(top?.[0]||'')||'Sem relato técnico detalhado',last:g.last,salesUnits,incidencePerThousand:salesUnits>0?g.occurrences/salesUnits*1000:null}}).sort((a,b)=>b.occurrences-a.occurrences);
   const defectMap=new Map<string,number>();records.forEach(r=>defectMap.set(r.defect,(defectMap.get(r.defect)||0)+1));const defectRows=[...defectMap.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,8);
   const monthMap=new Map<string,number>();records.forEach(r=>{const d=new Date(r.createdAt),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;monthMap.set(k,(monthMap.get(k)||0)+1)});const monthly=[...monthMap.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-12).map(([month,occurrences])=>({month:month.slice(5)+'/'+month.slice(2,4),occurrences}));
   const rateRows=modelRows.filter(r=>r.salesUnits>0).sort((a,b)=>(b.incidencePerThousand||0)-(a.incidencePerThousand||0)).slice(0,10);const totalSales=[...salesByProduct.values()].reduce((a,b)=>a+b,0),comparableOccurrences=modelRows.filter(r=>r.salesUnits>0).reduce((s,r)=>s+r.occurrences,0);return{records,modelRows,defectRows,monthly,total:records.length,critical:records.filter(r=>r.critical).length,unclassified:records.filter(r=>r.defect==='Defeito ainda não classificado').length,unlinked:records.filter(r=>!r.product).length,totalSales,overallRate:totalSales>0?comparableOccurrences/totalSales*1000:null,rateRows};
 },[tickets,products,sales,period]);
 const visibleRows=useMemo(()=>{const q=normalize(intelQuery);return intelligence.modelRows.filter(r=>!q||[r.name,r.model,r.sku,r.brand,r.manufacturer,r.topDefect,r.topReport].some(v=>normalize(v).includes(q)))},[intelligence.modelRows,intelQuery]);
 const openCreate=()=>{setDraft(empty);setEditing(null);setCreating(true);setError('');setMessage('')};
 const openEdit=(p:Product)=>{setCreating(false);setEditing(p);setDraft({name:p.name||'',codeSku:p.codeSku||'',description:p.description||'',model:p.model||'',brand:p.brand||'Procirúrgica',anvisaRegister:p.anvisaRegister||'',supplierName:p.supplierName||'',manufacturerName:p.manufacturerName||'',importerName:p.importerName||'',distributorName:p.distributorName||'',countryOrigin:p.countryOrigin||'',imageUrl:p.imageUrl||''});setError('');setMessage('')};
 const close=()=>{setCreating(false);setEditing(null)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft.name.trim()||!draft.codeSku.trim()){setError('Nome e SKU são obrigatórios.');return}setBusy(true);setError('');try{if(creating)await productMasterService.create(draft as ProductCreateInput);else if(editing)await productMasterService.update(editing.id,draft as ProductMasterChanges);setMessage(creating?'Produto cadastrado e disponível para novos SACs.':'Produto atualizado com auditoria.');close();await load();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));await onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar produto.')}finally{setBusy(false)}};
 const toggle=async(p:Product)=>{if(!allowed)return;const active=p.isActive===false,action=active?'reativar':'inativar';if(!window.confirm(`Deseja ${action} ${p.name}?`))return;setBusy(true);try{await productMasterService.setActive(p.id,active);await load()}catch(e){setError(e instanceof Error?e.message:`Falha ao ${action}.`)}finally{setBusy(false)}};
 const exportCsv=()=>{const rows=[['Posição','Produto','Modelo','SKU','Marca','Fabricante','Ocorrências','Críticas','Unidades vendidas','Índice por 1.000','Principal defeito','Relato real','Última ocorrência'],...visibleRows.map((r,i)=>[i+1,r.name,r.model,r.sku,r.brand,r.manufacturer,r.occurrences,r.critical,r.salesUnits||'',r.incidencePerThousand==null?'Sem base':r.incidencePerThousand.toFixed(3),r.topDefect,r.topReport,new Date(r.last).toLocaleDateString('pt-BR')])];const csv=rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`sacproh-inteligencia-produtos-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
 const importSales=async(file:File)=>{setBusy(true);setError('');setImportInfo('Lendo e validando o arquivo…');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:'',raw:true});if(!raw.length)throw new Error('A planilha não possui linhas de venda.');const rows=raw.map(r=>({periodStart:excelDate(pick(r,['Data Inicial','Data','Emissão','Dt Emissão','Periodo Inicial'])),periodEnd:excelDate(pick(r,['Data Final','Data','Emissão','Dt Emissão','Periodo Final'])),sku:String(pick(r,['SKU','Código','Codigo','Cod Produto','Código Produto'])).trim(),productName:String(pick(r,['Produto','Descrição','Descricao','Nome Produto'])).trim(),model:String(pick(r,['Modelo','Model'])).trim(),unitsSold:Math.round(toNumber(pick(r,['Quantidade','Qtd','Unidades','Qtde','Quantidade Vendida']))),customersCount:Math.round(toNumber(pick(r,['Clientes','Qtd Clientes','Quantidade Clientes']))),revenue:toNumber(pick(r,['Faturamento','Valor','Valor Total','Receita']))})).filter(r=>r.periodStart&&r.unitsSold>=0&&(r.sku||r.productName||r.model));if(!rows.length)throw new Error('Não encontrei linhas válidas. Use colunas de data, produto/SKU e quantidade.');const result=await salesVolumeService.importBatch(rows,file.name);setImportInfo(`${result.inserted.toLocaleString('pt-BR')} linhas importadas. ${result.unmatched?`${result.unmatched} ainda sem vínculo com produto mestre.`:'Todos os registros foram vinculados ao catálogo.'}`);await load();setTab('intelligence')}catch(e){setError(e instanceof Error?e.message:'Falha ao importar vendas.');setImportInfo('')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}};
 const field=(key:keyof Draft,label:string,placeholder='')=><label className="text-xs font-bold text-slate-700">{label}<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={placeholder} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-500"/></label>;
 const card=(label:string,value:string,note:string,color='text-[#145EDB]')=><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-extrabold uppercase tracking-wide text-slate-500">{label}</p><p className={`mt-1 text-2xl font-black ${color}`}>{value}</p><p className="mt-1 text-[10px] text-slate-400">{note}</p></div>;
 return <div className="space-y-5 pb-8">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="w-7 h-7 text-[#145EDB]"/><h1 className="text-2xl font-extrabold text-[#10233F]">Produtos & Inteligência de Qualidade</h1></div><p className="text-sm text-slate-500 mt-1">Produto canônico, recorrência, defeito real e incidência por 1.000 unidades vendidas.</p></div><div className="flex flex-wrap items-center gap-2"><select value={period} onChange={e=>setPeriod(e.target.value as Period)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold shadow-sm"><option value="90">Últimos 90 dias</option><option value="365">Últimos 12 meses</option><option value="all">Todo o histórico</option></select><button onClick={exportCsv} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold text-slate-700 shadow-sm flex items-center gap-2"><Download className="w-4 h-4"/>Exportar</button>{salesAllowed&&<><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>e.target.files?.[0]&&void importSales(e.target.files[0])}/><button disabled={busy} onClick={()=>fileRef.current?.click()} className="rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-2.5 text-xs font-bold shadow-sm flex items-center gap-2 disabled:opacity-50"><UploadCloud className="w-4 h-4"/>Importar vendas</button></>}</div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}{importInfo&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-semibold text-blue-800">{importInfo}</div>}
  <div className="flex gap-2 border-b border-slate-200 pb-2"><button onClick={()=>setTab('intelligence')} className={`px-3 py-2 rounded-lg text-xs font-bold ${tab==='intelligence'?'bg-[#145EDB] text-white':'bg-white text-slate-600 border'}`}>Inteligência</button><button onClick={()=>setTab('sales')} className={`px-3 py-2 rounded-lg text-xs font-bold ${tab==='sales'?'bg-[#145EDB] text-white':'bg-white text-slate-600 border'}`}>Base de vendas</button><button onClick={()=>setTab('catalog')} className={`px-3 py-2 rounded-lg text-xs font-bold ${tab==='catalog'?'bg-[#145EDB] text-white':'bg-white text-slate-600 border'}`}>Catálogo mestre</button></div>
  {tab==='intelligence'&&<>
   <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{card('Ocorrências',integer(intelligence.total),'SACs únicos por produto')}{card('Unid. vendidas',integer(intelligence.totalSales),'Base importada no período','text-emerald-600')}{card('Índice / 1.000',intelligence.overallRate==null?'Sem base':intelligence.overallRate.toFixed(3),'Somente produtos com denominador','text-violet-600')}{card('Críticas',integer(intelligence.critical),'Risco, dano ou prioridade crítica','text-red-600')}{card('Não classificadas',integer(intelligence.unclassified),'Defeito ainda sem taxonomia','text-amber-600')}{card('Sem vínculo',integer(intelligence.unlinked),'Pendências de saneamento','text-slate-600')}</div>
   {!sales.length&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 flex gap-3"><FileSpreadsheet className="w-5 h-5 text-amber-600 flex-none"/><div><p className="font-bold text-amber-900">O índice por mil ainda não pode ser calculado.</p><p className="text-xs text-amber-800 mt-1">Importe o histórico de vendas da Procirúrgica. O sistema usa produto + período como denominador e nunca assume venda zero como dado real.</p></div></div>}
   <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border bg-white p-4"><h3 className="font-extrabold text-[#10233F]">Top produtos por ocorrências</h3><div className="h-72 mt-3"><ResponsiveContainer><BarChart data={intelligence.modelRows.slice(0,10).map(r=>({name:productLabel(r.name,r.model),value:r.occurrences}))} layout="vertical" margin={{left:35,right:15}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={145} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="value" fill="#145EDB" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl border bg-white p-4"><h3 className="font-extrabold text-[#10233F]">Maior incidência por 1.000 vendidas</h3><p className="text-[10px] text-slate-500">Só aparecem produtos com base de vendas importada.</p><div className="h-72 mt-2"><ResponsiveContainer><BarChart data={intelligence.rateRows.map(r=>({name:productLabel(r.name,r.model),value:Number((r.incidencePerThousand||0).toFixed(3))}))} layout="vertical" margin={{left:35,right:15}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={145} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="value" fill="#7c3aed" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></div></div>
   <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-2xl border bg-white p-4"><h3 className="font-extrabold text-[#10233F]">Principais modos de falha</h3><div className="h-64 mt-3"><ResponsiveContainer><BarChart data={intelligence.defectRows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:9}} interval={0} angle={-15} textAnchor="end" height={70}/><YAxis/><Tooltip/><Bar dataKey="value">{intelligence.defectRows.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl border bg-white p-4"><h3 className="font-extrabold text-[#10233F]">Tendência de ocorrências</h3><div className="h-64 mt-3"><ResponsiveContainer><LineChart data={intelligence.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line type="monotone" dataKey="occurrences" stroke="#145EDB" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></div>
   <div className="rounded-2xl border bg-white overflow-hidden"><div className="p-4 flex flex-wrap items-center justify-between gap-3 border-b"><div><h3 className="font-extrabold text-[#10233F]">Ranking detalhado por produto canônico</h3><p className="text-xs text-slate-500">Ocorrência absoluta + taxa por mil evitam leituras distorcidas.</p></div><div className="relative"><Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400"/><input value={intelQuery} onChange={e=>setIntelQuery(e.target.value)} placeholder="Produto, modelo, defeito…" className="pl-9 pr-3 py-2 rounded-lg border text-xs w-64"/></div></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500 uppercase text-[9px]"><tr><th className="p-3 text-left">#</th><th className="p-3 text-left">Produto / modelo</th><th className="p-3 text-right">SACs</th><th className="p-3 text-right">Críticas</th><th className="p-3 text-right">Vendidas</th><th className="p-3 text-right">/ 1.000</th><th className="p-3 text-left">Principal defeito</th><th className="p-3 text-left">Relato real</th></tr></thead><tbody>{visibleRows.map((r,i)=><tr key={r.key} className="border-t hover:bg-slate-50"><td className="p-3 font-black text-slate-500">{i+1}</td><td className="p-3 min-w-56"><div className="flex gap-3 items-start">{r.productId&&products.find(p=>p.id===r.productId)?.imageUrl?<img src={products.find(p=>p.id===r.productId)?.imageUrl} className="w-12 h-12 object-contain rounded-xl border bg-white"/>:<div className="w-12 h-12 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center"><Package className="w-5 h-5 text-[#145EDB]"/></div>}<div><b className="text-[#10233F]">{productLabel(r.name,r.model)}</b><div className="text-[9px] text-slate-400 mt-1">Marca {r.brand||'Procirúrgica'}{r.sku?` · SKU ${r.sku}`:''}</div><div className="text-[9px] text-slate-400">{r.manufacturer?`Fabricante ${r.manufacturer}`:'Fabricante não informado'}</div></div></div></td><td className="p-3 text-right font-black text-[#145EDB]">{r.occurrences}</td><td className={`p-3 text-right font-bold ${r.critical?'text-red-600':'text-slate-400'}`}>{r.critical}</td><td className="p-3 text-right font-bold">{r.salesUnits?integer(r.salesUnits):<span className="text-amber-600">Sem base</span>}</td><td className="p-3 text-right"><span className={`px-2 py-1 rounded-full font-black ${r.incidencePerThousand==null?'bg-slate-100 text-slate-500':'bg-violet-50 text-violet-700'}`}>{r.incidencePerThousand==null?'—':r.incidencePerThousand.toFixed(3)}</span></td><td className="p-3 min-w-44"><b>{r.topDefect}</b><div className="text-[9px] text-slate-400">{Math.round(r.topDefectCount/Math.max(1,r.occurrences)*100)}% das ocorrências</div></td><td className="p-3 text-[10px] text-slate-500 min-w-64">{r.topReport}</td></tr>)}</tbody></table></div></div>
  </>}
  {tab==='sales'&&<div className="space-y-4"><div className="rounded-2xl border bg-white p-5 flex flex-wrap justify-between gap-4"><div><h3 className="font-extrabold text-[#10233F] flex gap-2 items-center"><FileSpreadsheet className="w-5 h-5 text-emerald-600"/>Base histórica de vendas</h3><p className="text-xs text-slate-500 mt-1">Denominador oficial para calcular ocorrências por 1.000 unidades vendidas.</p></div>{salesAllowed&&<button onClick={()=>fileRef.current?.click()} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold">Importar Excel/CSV</button>}</div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{card('Linhas',integer(sales.length),'Registros importados')}{card('Unidades',integer(sales.reduce((s,r)=>s+r.unitsSold,0)),'Todo histórico importado','text-emerald-600')}{card('Receita',money(sales.reduce((s,r)=>s+(r.revenue||0),0)),'Quando disponível','text-blue-600')}{card('Sem vínculo',integer(sales.filter(r=>!r.productId).length),'Precisam de saneamento','text-amber-600')}</div><div className="rounded-2xl border bg-white overflow-hidden"><table className="w-full text-xs"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr><th className="p-3 text-left">Período</th><th className="p-3 text-left">Produto</th><th className="p-3">SKU</th><th className="p-3 text-right">Unidades</th><th className="p-3 text-right">Receita</th><th className="p-3 text-left">Arquivo</th></tr></thead><tbody>{sales.slice().reverse().slice(0,200).map(r=><tr key={r.id} className="border-t"><td className="p-3">{new Date(r.periodStart+'T00:00:00').toLocaleDateString('pt-BR')}</td><td className="p-3"><b>{r.productName}</b>{r.model&&<div className="text-[9px] text-slate-400">{r.model}</div>}</td><td className="p-3 text-center">{r.sku||'—'}</td><td className="p-3 text-right font-bold">{integer(r.unitsSold)}</td><td className="p-3 text-right">{money(r.revenue)}</td><td className="p-3 text-slate-500">{r.sourceFile||'—'}</td></tr>)}</tbody></table>{sales.length>200&&<div className="p-3 text-xs text-slate-500 border-t">Exibindo os 200 registros mais recentes. O cálculo usa toda a base.</div>}</div></div>}
  {tab==='catalog'&&<div className="space-y-4"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{card('Catálogo',integer(stats.total),'Produtos cadastrados')}{card('Ativos',integer(stats.active),'Disponíveis para o SAC','text-emerald-600')}{card('Sem ANVISA',integer(stats.noAnvisa),'Revisar quando aplicável','text-amber-600')}{card('Sem descrição',integer(stats.noDescription),'Enriquecimento pendente','text-slate-600')}</div><div className="rounded-2xl border bg-white p-4 flex flex-wrap gap-3 justify-between"><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar produto…" className="rounded-lg border px-3 py-2 text-xs w-72"/><label className="text-xs flex items-center gap-2"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Inativos</label></div>{allowed&&<button onClick={openCreate} className="px-4 py-2 rounded-xl bg-[#145EDB] text-white text-xs font-bold flex items-center gap-2"><PackagePlus className="w-4 h-4"/>Novo produto</button>}</div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{filtered.map(p=><div key={p.id} className="rounded-2xl border bg-white p-4 flex gap-3"><div className="w-16 h-16 rounded-xl border bg-slate-50 flex items-center justify-center overflow-hidden">{p.imageUrl?<img src={p.imageUrl} className="w-full h-full object-contain"/>:<Package className="w-6 h-6 text-slate-400"/>}</div><div className="flex-1 min-w-0"><b className="text-sm text-[#10233F]">{productLabel(p.name,p.model||'')}</b><div className="text-[10px] text-slate-500 mt-1">SKU {p.codeSku} · {p.brand||'Procirúrgica'}</div><div className="text-[10px] text-slate-400">{p.manufacturerName||'Fabricante não informado'}</div>{allowed&&<div className="flex gap-2 mt-3"><button onClick={()=>openEdit(p)} className="text-[10px] font-bold text-[#145EDB] flex gap-1 items-center"><Edit3 className="w-3 h-3"/>Editar</button><button onClick={()=>void toggle(p)} className="text-[10px] font-bold text-slate-500 flex gap-1 items-center"><Power className="w-3 h-3"/>{p.isActive===false?'Reativar':'Inativar'}</button></div>}</div></div>)}</div></div>}
  {(creating||editing)&&<div className="fixed inset-0 z-[90] bg-black/50 flex items-start justify-center p-4 overflow-auto"><form onSubmit={save} className="mt-8 w-full max-w-4xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex justify-between items-start mb-4"><div><h3 className="font-extrabold text-lg text-[#10233F]">{creating?'Cadastrar produto':'Editar produto mestre'}</h3><p className="text-xs text-slate-500">A alteração é auditada e passa a alimentar novos SACs.</p></div><button type="button" onClick={close}><X className="w-5 h-5"/></button></div><div className="grid md:grid-cols-3 gap-3">{field('name','Nome oficial')}{field('model','Modelo')}{field('codeSku','SKU / código')}{field('brand','Marca')}{field('manufacturerName','Fabricante')}{field('anvisaRegister','Registro ANVISA')}{field('supplierName','Fornecedor')}{field('importerName','Importador')}{field('distributorName','Distribuidor')}{field('countryOrigin','País de origem')}{field('imageUrl','URL da imagem oficial')}<label className="md:col-span-3 text-xs font-bold text-slate-700">Descrição técnica<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} rows={3} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"/></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={close} className="px-4 py-2 rounded-lg border text-xs font-bold">Cancelar</button><button disabled={busy} className="px-4 py-2 rounded-lg bg-[#145EDB] text-white text-xs font-bold disabled:opacity-50">{busy?'Salvando…':'Salvar produto'}</button></div></form></div>}
 </div>;
};
