import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Edit3,Package,PackagePlus,Power,Search,ShieldCheck,X} from 'lucide-react';
import type {Product} from '../../types';
import {productMasterService,ProductCreateInput,ProductMasterChanges} from '../../services/productMasterService';

type Props={currentUserRole:string;onChanged?:()=>void|Promise<void>};
type Draft={name:string;codeSku:string;description:string;model:string;brand:string;anvisaRegister:string;supplierName:string;manufacturerName:string;importerName:string;distributorName:string;countryOrigin:string};
const empty:Draft={name:'',codeSku:'',description:'',model:'',brand:'',anvisaRegister:'',supplierName:'',manufacturerName:'',importerName:'',distributorName:'',countryOrigin:''};
const canManage=(role:string)=>['SUPERADMIN','RESPONSAVEL_TECNICA','ADMIN_EMPRESA'].includes(role);

export const ProductCatalogModule:React.FC<Props>=({currentUserRole,onChanged})=>{
 const [products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(''),[showInactive,setShowInactive]=useState(false),[editing,setEditing]=useState<Product|null>(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState<Draft>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const allowed=canManage(currentUserRole);
 const load=async()=>{setError('');try{setProducts(await productMasterService.list())}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar produtos.')}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>products.filter(p=>{if(!showInactive&&p.isActive===false)return false;const q=query.trim().toLowerCase();if(!q)return true;return [p.name,p.codeSku,p.model,p.brand,p.anvisaRegister,p.manufacturerName,p.supplierName].some(v=>String(v||'').toLowerCase().includes(q));}),[products,query,showInactive]);
 const stats=useMemo(()=>({total:products.length,active:products.filter(p=>p.isActive!==false).length,noAnvisa:products.filter(p=>p.isActive!==false&&!p.anvisaRegister).length,noDescription:products.filter(p=>p.isActive!==false&&!p.description).length}),[products]);
 const openCreate=()=>{setDraft(empty);setEditing(null);setCreating(true);setError('');setMessage('')};
 const openEdit=(p:Product)=>{setCreating(false);setEditing(p);setDraft({name:p.name||'',codeSku:p.codeSku||'',description:p.description||'',model:p.model||'',brand:p.brand||'',anvisaRegister:p.anvisaRegister||'',supplierName:p.supplierName||'',manufacturerName:p.manufacturerName||'',importerName:p.importerName||'',distributorName:p.distributorName||'',countryOrigin:p.countryOrigin||''});setError('');setMessage('')};
 const close=()=>{setCreating(false);setEditing(null)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft.name.trim()||!draft.codeSku.trim()){setError('Nome e SKU são obrigatórios.');return}setBusy(true);setError('');try{if(creating)await productMasterService.create(draft as ProductCreateInput);else if(editing)await productMasterService.update(editing.id,draft as ProductMasterChanges);setMessage(creating?'Produto cadastrado e disponível para novos SACs.':'Produto atualizado com auditoria.');close();await load();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));await onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar produto.')}finally{setBusy(false)}};
 const toggle=async(p:Product)=>{if(!allowed)return;const active=p.isActive===false;const action=active?'reativar':'inativar';if(!window.confirm(`Deseja ${action} ${p.name}?`))return;setBusy(true);setError('');try{await productMasterService.setActive(p.id,active);setMessage(`Produto ${active?'reativado':'inativado'} com sucesso.`);await load();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));await onChanged?.()}catch(e){setError(e instanceof Error?e.message:`Falha ao ${action}.`)}finally{setBusy(false)}};
 const field=(key:keyof Draft,label:string,placeholder='')=><label className="text-xs font-bold text-slate-700">{label}<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={placeholder} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-[#145EDB]/20 focus:border-[#145EDB]"/></label>;
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Package className="w-6 h-6 text-[#145EDB]"/><h1 className="text-2xl font-extrabold text-[#10233F]">Produtos</h1></div><p className="text-sm text-slate-500 mt-1">Cadastro mestre usado na abertura do SAC, rastreabilidade, assistência técnica e relatórios regulatórios.</p></div>{allowed&&<button onClick={openCreate} className="rounded-xl bg-[#FF8500] hover:bg-[#e07500] text-white font-extrabold px-4 py-2.5 flex items-center gap-2 shadow-sm"><PackagePlus className="w-4 h-4"/>Cadastrar produto</button>}</div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[stats.total,'Total no catálogo',Package,'text-[#145EDB]'],[stats.active,'Produtos ativos',CheckCircle2,'text-emerald-600'],[stats.noAnvisa,'Sem ANVISA',ShieldCheck,'text-amber-600'],[stats.noDescription,'Sem descrição',AlertTriangle,'text-rose-600']].map(([v,l,I,c]:any)=><div key={l} className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><I className={`w-4 h-4 ${c}`}/><strong className="block text-2xl mt-2 text-[#10233F]">{v}</strong><span className="text-xs text-slate-500">{l}</span></div>)}</div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 text-red-700 p-3 text-sm">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-700 p-3 text-sm">{message}</div>}
  <section className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b flex flex-wrap gap-3 items-center justify-between"><div className="relative flex-1 min-w-[240px]"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, SKU, modelo, marca, ANVISA ou fabricante..." className="w-full pl-9 pr-3 py-2 rounded-lg border border-slate-200 text-sm"/></div><label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Mostrar inativos</label></div>
   <div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500 uppercase"><tr><th className="text-left p-3">Produto</th><th className="text-left p-3">SKU / Modelo</th><th className="text-left p-3">Regulatório</th><th className="text-left p-3">Fabricante / Origem</th><th className="text-left p-3">Status</th><th className="text-right p-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(p=><tr key={p.id} className={p.isActive===false?'bg-slate-50 opacity-70':''}><td className="p-3"><strong className="text-sm text-[#10233F]">{p.name}</strong><p className="text-slate-500 max-w-sm truncate">{p.description||'Descrição técnica não cadastrada'}</p><span className="text-[10px] text-slate-400">{p.brand||'Marca não informada'}</span></td><td className="p-3"><span className="font-mono font-bold">{p.codeSku}</span><p className="text-slate-500">{p.model||'-'}</p></td><td className="p-3"><span className={p.anvisaRegister?'text-emerald-700':'text-amber-700'}>{p.anvisaRegister||'ANVISA pendente'}</span></td><td className="p-3"><strong>{p.manufacturerName||p.supplierName||'-'}</strong><p className="text-slate-500">{p.countryOrigin||'-'}</p></td><td className="p-3"><span className={`px-2 py-1 rounded-full font-bold ${p.isActive===false?'bg-slate-200 text-slate-600':'bg-emerald-100 text-emerald-700'}`}>{p.isActive===false?'INATIVO':'ATIVO'}</span></td><td className="p-3"><div className="flex justify-end gap-2">{allowed&&<><button onClick={()=>openEdit(p)} className="p-2 rounded-lg border hover:bg-slate-50" title="Editar"><Edit3 className="w-4 h-4"/></button><button disabled={busy} onClick={()=>toggle(p)} className={`p-2 rounded-lg border ${p.isActive===false?'text-emerald-700':'text-rose-600'} hover:bg-slate-50`} title={p.isActive===false?'Reativar':'Inativar'}><Power className="w-4 h-4"/></button></>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="p-8 text-center text-slate-500">Nenhum produto encontrado.</td></tr>}</tbody></table></div>
  </section>
  {!allowed&&<div className="text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-xl p-3">Seu perfil pode consultar o catálogo. Cadastro e alterações são restritos a SuperADM, Responsável Técnica e Admin da Empresa.</div>}
  {(creating||editing)&&<div className="fixed inset-0 z-[90] bg-slate-900/60 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-4xl bg-white rounded-2xl shadow-2xl max-h-[92vh] overflow-y-auto"><div className="sticky top-0 bg-white p-5 border-b flex items-center justify-between"><div><h2 className="font-extrabold text-lg text-[#10233F]">{creating?'Cadastrar novo produto':'Editar produto'}</h2><p className="text-xs text-slate-500">Nome e SKU são obrigatórios. Os demais campos podem ser enriquecidos progressivamente.</p></div><button type="button" onClick={close}><X className="w-5 h-5"/></button></div><div className="p-5 space-y-4"><div className="grid md:grid-cols-2 gap-3">{field('name','Nome oficial*','Ex.: PRO8000 - Cadeira de Rodas')}{field('codeSku','SKU / Código*','Ex.: PRO8000')}{field('model','Modelo')}{field('brand','Marca')}{field('anvisaRegister','Registro ANVISA')}{field('supplierName','Fornecedor')}{field('manufacturerName','Fabricante')}{field('countryOrigin','País de origem')}{field('importerName','Importador')}{field('distributorName','Distribuidor')}</div><label className="block text-xs font-bold text-slate-700">Descrição técnica<textarea rows={5} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 p-3 font-normal" placeholder="Finalidade, principais características, apresentação e diferenciais técnicos factuais."/></label></div><div className="sticky bottom-0 bg-slate-50 border-t p-4 flex justify-end gap-2"><button type="button" onClick={close} className="px-4 py-2 rounded-lg bg-slate-200 font-bold">Cancelar</button><button disabled={busy} className="px-5 py-2 rounded-lg bg-[#145EDB] text-white font-extrabold">{busy?'Salvando...':creating?'Cadastrar produto':'Salvar alterações'}</button></div></form></div>}
 </div>;
};
