import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Edit3,PackagePlus,Power,Save,Search,X} from 'lucide-react';
import {productMasterAdvancedService,type ProductFamily,type ProductMasterRecord,type ProductMasterForm} from '../../services/productMasterAdvancedService';

type Props={currentUserRole:string;onChanged?:()=>void|Promise<void>};
type Draft={familyId:string;name:string;codeSku:string;description:string;model:string;brand:string;gtinEan:string;ncm:string;unitMeasure:string;manufacturerReference:string;supplierName:string;manufacturerName:string;importerName:string;distributorName:string;countryOrigin:string;imageUrl:string;regulatoryType:string;anvisaRegister:string;anvisaStatus:string;anvisaExpirationDate:string;anvisaRiskClass:string;inmetroRegister:string;inmetroExpirationDate:string;udiDi:string;lotControl:boolean;serialControl:boolean;expirationControl:boolean;shelfLifeMonths:string;warrantyMonths:string;intendedUse:string;technicalSpecifications:string;storageConditions:string;handlingNotes:string;accessoriesIncluded:string};
const empty:Draft={familyId:'',name:'',codeSku:'',description:'',model:'',brand:'Procirúrgica',gtinEan:'',ncm:'',unitMeasure:'UN',manufacturerReference:'',supplierName:'',manufacturerName:'',importerName:'',distributorName:'',countryOrigin:'',imageUrl:'',regulatoryType:'ANVISA',anvisaRegister:'',anvisaStatus:'',anvisaExpirationDate:'',anvisaRiskClass:'',inmetroRegister:'',inmetroExpirationDate:'',udiDi:'',lotControl:true,serialControl:false,expirationControl:false,shelfLifeMonths:'',warrantyMonths:'',intendedUse:'',technicalSpecifications:'',storageConditions:'',handlingNotes:'',accessoriesIncluded:''};
const canManage=(r:string)=>['SUPERADMIN','RESPONSAVEL_TECNICA','ADMIN_EMPRESA'].includes(r);
const clean=(v?:string)=>String(v||'').trim();
const completeness=(p:ProductMasterRecord)=>{const fields=[p.name,p.codeSku,p.description,p.model,p.brand,p.manufacturerName,p.countryOrigin,p.unitMeasure,p.intendedUse,p.technicalSpecifications];if(p.regulatoryType==='ANVISA'||p.regulatoryType==='BOTH')fields.push(p.anvisaRegister,p.anvisaStatus);if(p.regulatoryType==='INMETRO'||p.regulatoryType==='BOTH')fields.push(p.inmetroRegister);return Math.round(fields.filter(Boolean).length/fields.length*100)};
const toDraft=(p:ProductMasterRecord):Draft=>({familyId:p.familyId||'',name:p.name||'',codeSku:p.codeSku||'',description:p.description||'',model:p.model||'',brand:p.brand||'',gtinEan:p.gtinEan||'',ncm:p.ncm||'',unitMeasure:p.unitMeasure||'UN',manufacturerReference:p.manufacturerReference||'',supplierName:p.supplierName||'',manufacturerName:p.manufacturerName||'',importerName:p.importerName||'',distributorName:p.distributorName||'',countryOrigin:p.countryOrigin||'',imageUrl:p.imageUrl||'',regulatoryType:p.regulatoryType||'ANVISA',anvisaRegister:p.anvisaRegister||'',anvisaStatus:p.anvisaStatus||'',anvisaExpirationDate:p.anvisaExpirationDate||'',anvisaRiskClass:p.anvisaRiskClass||'',inmetroRegister:p.inmetroRegister||'',inmetroExpirationDate:p.inmetroExpirationDate||'',udiDi:p.udiDi||'',lotControl:p.lotControl,serialControl:p.serialControl,expirationControl:p.expirationControl,shelfLifeMonths:p.shelfLifeMonths==null?'':String(p.shelfLifeMonths),warrantyMonths:p.warrantyMonths==null?'':String(p.warrantyMonths),intendedUse:p.intendedUse||'',technicalSpecifications:p.technicalSpecifications||'',storageConditions:p.storageConditions||'',handlingNotes:p.handlingNotes||'',accessoriesIncluded:p.accessoriesIncluded||''});
const payload=(d:Draft):ProductMasterForm=>({familyId:d.familyId||undefined,name:clean(d.name),codeSku:clean(d.codeSku).toUpperCase(),description:clean(d.description)||undefined,model:clean(d.model)||undefined,brand:clean(d.brand)||undefined,gtinEan:clean(d.gtinEan)||undefined,ncm:clean(d.ncm)||undefined,unitMeasure:clean(d.unitMeasure)||undefined,manufacturerReference:clean(d.manufacturerReference)||undefined,supplierName:clean(d.supplierName)||undefined,manufacturerName:clean(d.manufacturerName)||undefined,importerName:clean(d.importerName)||undefined,distributorName:clean(d.distributorName)||undefined,countryOrigin:clean(d.countryOrigin)||undefined,imageUrl:clean(d.imageUrl)||undefined,regulatoryType:d.regulatoryType||undefined,anvisaRegister:clean(d.anvisaRegister)||undefined,anvisaStatus:clean(d.anvisaStatus)||undefined,anvisaExpirationDate:d.anvisaExpirationDate||undefined,anvisaRiskClass:clean(d.anvisaRiskClass)||undefined,inmetroRegister:clean(d.inmetroRegister)||undefined,inmetroExpirationDate:d.inmetroExpirationDate||undefined,udiDi:clean(d.udiDi)||undefined,lotControl:d.lotControl,serialControl:d.serialControl,expirationControl:d.expirationControl,shelfLifeMonths:d.shelfLifeMonths?Number(d.shelfLifeMonths):undefined,warrantyMonths:d.warrantyMonths?Number(d.warrantyMonths):undefined,intendedUse:clean(d.intendedUse)||undefined,technicalSpecifications:clean(d.technicalSpecifications)||undefined,storageConditions:clean(d.storageConditions)||undefined,handlingNotes:clean(d.handlingNotes)||undefined,accessoriesIncluded:clean(d.accessoriesIncluded)||undefined});

export const ProductMasterManagement:React.FC<Props>=({currentUserRole,onChanged})=>{
 const [products,setProducts]=useState<ProductMasterRecord[]>([]),[families,setFamilies]=useState<ProductFamily[]>([]),[query,setQuery]=useState(''),[showInactive,setShowInactive]=useState(false),[editing,setEditing]=useState<ProductMasterRecord|null>(null),[draft,setDraft]=useState<Draft>(empty),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[newFamily,setNewFamily]=useState('');
 const allowed=canManage(currentUserRole);
 const load=async()=>{const [p,f]=await Promise.all([productMasterAdvancedService.list(),productMasterAdvancedService.listFamilies()]);setProducts(p);setFamilies(f)};
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar catálogo.'))},[]);
 const filtered=useMemo(()=>products.filter(p=>(showInactive||p.isActive)&&[p.name,p.codeSku,p.model,p.brand,p.gtinEan,p.anvisaRegister,p.inmetroRegister,p.manufacturerName,p.familyName].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[products,query,showInactive]);
 const stats=useMemo(()=>({active:products.filter(p=>p.isActive).length,incomplete:products.filter(p=>p.isActive&&completeness(p)<80).length,regulated:products.filter(p=>p.isActive&&p.regulatoryType!=='NOT_APPLICABLE').length}),[products]);
 const startNew=()=>{setEditing(null);setDraft(empty);setNewFamily('');setOpen(true);setError('');setMessage('')};
 const startEdit=(p:ProductMasterRecord)=>{setEditing(p);setDraft(toDraft(p));setNewFamily('');setOpen(true);setError('');setMessage('')};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft.name.trim()||!draft.codeSku.trim()){setError('Nome oficial e SKU são obrigatórios.');return}setBusy(true);setError('');try{let familyId=draft.familyId;if(newFamily.trim()){const family=await productMasterAdvancedService.createFamily(newFamily.trim());familyId=family.id;setDraft(v=>({...v,familyId}))}const data=payload({...draft,familyId});if(editing)await productMasterAdvancedService.update(editing.id,data);else await productMasterAdvancedService.create(data);await load();await onChanged?.();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));setMessage(editing?'Produto atualizado com rastreabilidade de auditoria.':'Produto cadastrado e liberado para utilização nos novos SACs.');setOpen(false)}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar o produto.')}finally{setBusy(false)}};
 const toggle=async(p:ProductMasterRecord)=>{if(!allowed)return;if(!confirm(`${p.isActive?'Inativar':'Reativar'} ${p.name}?`))return;try{await productMasterAdvancedService.setActive(p.id,!p.isActive);await load()}catch(err){setError(err instanceof Error?err.message:'Falha ao alterar status.')}};
 const input=(key:keyof Draft,label:string,placeholder='',type='text')=><label className="text-xs font-bold text-slate-700">{label}<input type={type} value={String(draft[key]??'')} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={placeholder} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>;
 const textarea=(key:keyof Draft,label:string,rows=3)=><label className="text-xs font-bold text-slate-700">{label}<textarea rows={rows} value={String(draft[key]??'')} onChange={e=>setDraft({...draft,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>;
 return <div className="space-y-5">
  <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#145EDB]">SACPROH · Cadastro mestre</p><h1 className="text-2xl font-black text-[#10233F]">Produtos, rastreabilidade e dados regulatórios</h1><p className="mt-1 text-xs text-slate-500">Cadastro completo para abertura de SAC, rastreabilidade, relatórios, ANVISA/Inmetro e análise de qualidade.</p></div>{allowed&&<button onClick={startNew} className="self-start rounded-xl bg-[#145EDB] px-4 py-2.5 text-xs font-bold text-white flex items-center gap-2"><PackagePlus className="w-4 h-4"/>Cadastrar novo produto</button>}</div></section>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Stat label="Produtos ativos" value={stats.active}/><Stat label="Cadastro < 80%" value={stats.incomplete} alert={stats.incomplete>0}/><Stat label="Regulados" value={stats.regulated}/><Stat label="Famílias" value={families.length}/></div>
  <section className="rounded-2xl border bg-white shadow-sm overflow-hidden"><div className="p-4 border-b flex flex-wrap justify-between gap-3"><div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Produto, SKU, modelo, GTIN, registro..." className="pl-9 pr-3 py-2 rounded-lg border text-xs w-80"/></div><label className="text-xs flex gap-2 items-center"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Mostrar inativos</label></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-3 text-left">Produto</th><th className="p-3 text-left">Identificação</th><th className="p-3 text-left">Regulatório</th><th className="p-3 text-left">Controles</th><th className="p-3 text-center">Completude</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(p=>{const c=completeness(p);return <tr key={p.id} className="border-t align-top hover:bg-slate-50"><td className="p-3"><b className="text-[#10233F]">{p.name}</b><div className="text-slate-500">{p.model||'Sem modelo'} · {p.brand||'Sem marca'}</div><div className="text-[10px] text-slate-400">{p.familyName||'Sem família'} · {p.manufacturerName||'Fabricante não informado'}</div></td><td className="p-3"><div><b>SKU:</b> {p.codeSku}</div><div><b>GTIN:</b> {p.gtinEan||'—'}</div><div><b>NCM:</b> {p.ncm||'—'}</div></td><td className="p-3"><div>{p.regulatoryType||'—'}</div><div className="text-slate-500">ANVISA {p.anvisaRegister||'—'}</div><div className="text-slate-500">Inmetro {p.inmetroRegister||'—'}</div></td><td className="p-3"><div>Lote: {p.lotControl?'Sim':'Não'} · Série: {p.serialControl?'Sim':'Não'}</div><div>Validade: {p.expirationControl?'Sim':'Não'} · Garantia: {p.warrantyMonths?`${p.warrantyMonths} meses`:'—'}</div></td><td className="p-3 text-center"><span className={`inline-flex rounded-full px-2 py-1 font-black ${c>=90?'bg-emerald-100 text-emerald-700':c>=70?'bg-amber-100 text-amber-800':'bg-red-100 text-red-700'}`}>{c}%</span></td><td className="p-3 whitespace-nowrap">{allowed&&<div className="flex gap-2"><button onClick={()=>startEdit(p)} className="text-[#145EDB] font-bold flex gap-1"><Edit3 className="w-3.5 h-3.5"/>Editar</button><button onClick={()=>void toggle(p)} className="text-slate-500 font-bold flex gap-1"><Power className="w-3.5 h-3.5"/>{p.isActive?'Inativar':'Reativar'}</button></div>}</td></tr>})}</tbody></table></div></section>
  {open&&<div className="fixed inset-0 z-[100] bg-black/55 overflow-y-auto p-4"><form onSubmit={save} className="mx-auto my-4 max-w-6xl rounded-2xl bg-white shadow-2xl overflow-hidden"><div className="sticky top-0 z-10 bg-[#0B2343] text-white px-5 py-4 flex justify-between"><div><h2 className="font-black text-lg">{editing?'Editar cadastro completo':'Novo produto'}</h2><p className="text-xs text-blue-100">Preencha os dados de identificação, regulatórios, rastreabilidade e uso técnico.</p></div><button type="button" onClick={()=>setOpen(false)}><X className="w-5 h-5"/></button></div><div className="p-5 space-y-6">
   <Block title="1. Identificação e comercial"><div className="grid md:grid-cols-3 gap-3">{input('name','Nome oficial *')}{input('model','Modelo')}{input('codeSku','SKU / código interno *')}{input('gtinEan','GTIN / EAN')}{input('ncm','NCM')}{input('unitMeasure','Unidade de medida','UN, CX, KIT...')}{input('brand','Marca')}{input('manufacturerReference','Referência do fabricante')}{input('imageUrl','URL da imagem oficial')}<label className="text-xs font-bold text-slate-700">Família<select value={draft.familyId} onChange={e=>setDraft({...draft,familyId:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"><option value="">Sem família</option>{families.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{input('countryOrigin','País de origem')}<label className="text-xs font-bold text-slate-700">Criar nova família<input value={newFamily} onChange={e=>setNewFamily(e.target.value)} placeholder="Ex.: Mobilidade" className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"/></label></div><div className="mt-3">{textarea('description','Descrição técnica / comercial completa',4)}</div></Block>
   <Block title="2. Cadeia de fornecimento"><div className="grid md:grid-cols-4 gap-3">{input('manufacturerName','Fabricante')}{input('supplierName','Fornecedor')}{input('importerName','Importador')}{input('distributorName','Distribuidor')}</div></Block>
   <Block title="3. Regulatório"><div className="grid md:grid-cols-4 gap-3"><label className="text-xs font-bold text-slate-700">Enquadramento<select value={draft.regulatoryType} onChange={e=>setDraft({...draft,regulatoryType:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal"><option value="ANVISA">ANVISA</option><option value="INMETRO">Inmetro</option><option value="BOTH">ANVISA + Inmetro</option><option value="NOT_APPLICABLE">Não aplicável</option></select></label>{input('anvisaRegister','Registro ANVISA')}{input('anvisaStatus','Situação ANVISA','Ativo, vigente, isento...')}{input('anvisaRiskClass','Classe de risco')}{input('anvisaExpirationDate','Validade ANVISA','', 'date')}{input('inmetroRegister','Registro/certificação Inmetro')}{input('inmetroExpirationDate','Validade Inmetro','', 'date')}{input('udiDi','UDI-DI')}</div></Block>
   <Block title="4. Rastreabilidade e vida útil"><div className="grid md:grid-cols-3 gap-3"><Toggle label="Controla lote" value={draft.lotControl} onChange={v=>setDraft({...draft,lotControl:v})}/><Toggle label="Controla número de série" value={draft.serialControl} onChange={v=>setDraft({...draft,serialControl:v})}/><Toggle label="Controla validade" value={draft.expirationControl} onChange={v=>setDraft({...draft,expirationControl:v})}/>{input('shelfLifeMonths','Vida útil / validade (meses)','', 'number')}{input('warrantyMonths','Garantia (meses)','', 'number')}</div></Block>
   <Block title="5. Uso e especificações"><div className="grid md:grid-cols-2 gap-3">{textarea('intendedUse','Uso pretendido / indicação',4)}{textarea('technicalSpecifications','Especificações técnicas',4)}{textarea('accessoriesIncluded','Acessórios e componentes incluídos',3)}{textarea('storageConditions','Condições de armazenamento',3)}{textarea('handlingNotes','Cuidados, manuseio e observações',3)}</div></Block>
   <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900 flex gap-2"><CheckCircle2 className="w-4 h-4 flex-none"/><span>Os dados salvos passam a alimentar novos SACs e relatórios. Protocolos históricos mantêm o snapshot original para preservar auditoria.</span></div>
   </div><div className="sticky bottom-0 bg-white border-t p-4 flex justify-end gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2 text-xs font-bold">Cancelar</button><button disabled={busy} className="rounded-lg bg-[#145EDB] text-white px-5 py-2 text-xs font-bold flex items-center gap-2 disabled:opacity-50"><Save className="w-4 h-4"/>{busy?'Salvando...':'Salvar cadastro completo'}</button></div></form></div>}
 </div>;
};
const Block:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><section className="rounded-xl border border-slate-200 p-4"><h3 className="font-black text-sm text-[#10233F] mb-3">{title}</h3>{children}</section>;
const Toggle:React.FC<{label:string;value:boolean;onChange:(v:boolean)=>void}>=({label,value,onChange})=><label className="rounded-lg border p-3 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;
const Stat:React.FC<{label:string;value:number;alert?:boolean}>=({label,value,alert})=><article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-[10px] uppercase font-black text-slate-500">{label}</p>{alert?<AlertTriangle className="w-4 h-4 text-amber-500"/>:<CheckCircle2 className="w-4 h-4 text-emerald-500"/>}</div><p className="text-2xl font-black text-[#10233F]">{value}</p></article>;
