import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Armchair,BarChart3,BedDouble,Bike,CalendarDays,CheckCircle2,Cog,Download,Edit3,Filter,Package,PackagePlus,Power,Search,ShieldAlert,Target,TrendingUp,Wrench,X} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import type {Product,Ticket,TicketItem} from '../../types';
import {productMasterService,ProductCreateInput,ProductMasterChanges} from '../../services/productMasterService';
import {apiService} from '../../services/apiService';

type Props={currentUserRole:string;onChanged?:()=>void|Promise<void>};
type Draft={name:string;codeSku:string;description:string;model:string;brand:string;anvisaRegister:string;supplierName:string;manufacturerName:string;importerName:string;distributorName:string;countryOrigin:string};
type Period='90'|'365'|'all';
type IntelligenceRow={key:string;productId?:string;name:string;model:string;sku:string;brand:string;occurrences:number;critical:number;topDefect:string;topDefectCount:number;topReport:string;last:string};
const empty:Draft={name:'',codeSku:'',description:'',model:'',brand:'',anvisaRegister:'',supplierName:'',manufacturerName:'',importerName:'',distributorName:'',countryOrigin:''};
const canManage=(role:string)=>['SUPERADMIN','RESPONSAVEL_TECNICA','ADMIN_EMPRESA'].includes(role);
const COLORS=['#ef4444','#f59e0b','#eab308','#22c55e','#3b82f6','#8b5cf6','#64748b','#06b6d4'];
const normalize=(v?:string)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const clean=(v?:string)=>String(v||'').replace(/\s+/g,' ').trim();
const genericDefect=(v?:string)=>{const n=normalize(v);return !n||['reclamacao de produto','reclamacao produto','produto','outros','outro','nao classificado','sem classificacao','defeito de produto'].includes(n)};
const defectFromTicket=(t:Ticket)=>{
  const structured=[t.classification,t.subcategory,t.category].map(clean).find(v=>!genericDefect(v));
  if(structured)return structured!;
  const text=normalize([t.description,t.classification,t.subcategory].filter(Boolean).join(' '));
  const rules:[RegExp,string][]=[
    [/(freio|travamento|trava|nao freia|não freia)/,'Falha no sistema de freio'],
    [/(motor|eletric|energia|nao liga|não liga|acionamento|controle|painel)/,'Falha elétrica / motor'],
    [/(quebr|fratur|trinc|romp|solda|estrutura)/,'Quebra / falha estrutural'],
    [/(roda|rodizio|rodízio|pneu|eixo)/,'Falha em roda / rodízio'],
    [/(vazamento|vaza|liquido|líquido)/,'Vazamento'],
    [/(rasg|estof|revest|tecido|couro)/,'Estofamento / revestimento danificado'],
    [/(falt.*peca|falta.*peça|ausente|nao veio|não veio|incomplet)/,'Componente ausente / produto incompleto'],
    [/(ruido|ruído|barulho|rangido)/,'Ruído anormal'],
    [/(montagem|montar|ajuste|desalinh|folg)/,'Montagem / ajuste'],
    [/(bateria|carregador|carga)/,'Bateria / alimentação'],
    [/(ferrug|oxid|pintura|acabamento|descasc)/,'Acabamento / oxidação'],
    [/(deform|amass|avaria|transporte|embalagem)/,'Avaria / deformação'],
    [/(costura|velcro|cinto|faixa)/,'Falha em acessório / fixação']
  ];
  for(const [re,label] of rules)if(re.test(text))return label;
  return 'Defeito ainda não classificado';
};
const reportSnippet=(t:Ticket)=>{const d=clean(t.description);return d?d.length>92?d.slice(0,89)+'…':d:'Sem relato técnico detalhado';};
const productLabel=(name:string,model:string)=>{const n=clean(name)||'Produto não identificado',m=clean(model);return m&&!normalize(n).includes(normalize(m))?`${n} ${m}`:n};
const resolveProduct=(item:TicketItem,byId:Map<string,Product>,bySku:Map<string,Product>,byName:Map<string,Product>)=>{
  if(item.productId&&byId.has(item.productId))return byId.get(item.productId);
  const sku=normalize(item.sku);if(sku&&bySku.has(sku))return bySku.get(sku);
  const name=normalize(item.productName);if(name&&byName.has(name))return byName.get(name);
  return undefined;
};

export const ProductCatalogModule:React.FC<Props>=({currentUserRole,onChanged})=>{
 const [products,setProducts]=useState<Product[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[query,setQuery]=useState(''),[showInactive,setShowInactive]=useState(false),[editing,setEditing]=useState<Product|null>(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState<Draft>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState<'catalog'|'intelligence'>('intelligence'),[period,setPeriod]=useState<Period>('365'),[intelQuery,setIntelQuery]=useState('');
 const allowed=canManage(currentUserRole);
 const load=async()=>{setError('');try{const [catalog,occurrences]=await Promise.all([productMasterService.list(),apiService.getTickets()]);setProducts(catalog);setTickets(occurrences)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar produtos e indicadores.')}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>products.filter(p=>{if(!showInactive&&p.isActive===false)return false;const q=normalize(query);if(!q)return true;return [p.name,p.codeSku,p.model,p.brand,p.anvisaRegister,p.manufacturerName,p.supplierName].some(v=>normalize(v).includes(q));}),[products,query,showInactive]);
 const stats=useMemo(()=>({total:products.length,active:products.filter(p=>p.isActive!==false).length,noAnvisa:products.filter(p=>p.isActive!==false&&!p.anvisaRegister).length,noDescription:products.filter(p=>p.isActive!==false&&!p.description).length}),[products]);
 const intelligence=useMemo(()=>{
   const now=Date.now(),cutoff=period==='all'?0:now-Number(period)*86400000;
   const byId=new Map(products.map(p=>[p.id,p])),bySku=new Map(products.filter(p=>p.codeSku).map(p=>[normalize(p.codeSku),p])),byName=new Map(products.filter(p=>p.name).map(p=>[normalize(p.name),p]));
   const source=tickets.filter(t=>!cutoff||new Date(t.createdAt).getTime()>=cutoff);
   const seen=new Set<string>();
   const records:{key:string;product?:Product;name:string;model:string;sku:string;brand:string;defect:string;report:string;critical:boolean;createdAt:string}[]=[];
   source.forEach(ticket=>ticket.items.forEach(item=>{
     const product=resolveProduct(item,byId,bySku,byName);
     const name=clean(product?.name||item.productName)||'Produto não identificado';
     const model=clean(product?.model||item.productModel)||'';
     const sku=clean(product?.codeSku||item.sku)||'';
     const canonical=product?.id||`${normalize(name)}|${normalize(model)}`;
     const occurrenceKey=`${ticket.id}:${canonical}`;if(seen.has(occurrenceKey))return;seen.add(occurrenceKey);
     records.push({key:canonical,product,name,model,sku,brand:clean(product?.brand)||'',defect:defectFromTicket(ticket),report:reportSnippet(ticket),critical:ticket.priority==='CRITICAL'||ticket.userRiskFlag||ticket.adverseEventFlag||ticket.damageFlag,createdAt:ticket.createdAt});
   }));
   const groups=new Map<string,{key:string;productId?:string;name:string;model:string;sku:string;brand:string;occurrences:number;critical:number;defects:Map<string,number>;reports:Map<string,string>;last:string}>();
   records.forEach(r=>{const g=groups.get(r.key)||{key:r.key,productId:r.product?.id,name:r.name,model:r.model,sku:r.sku,brand:r.brand,occurrences:0,critical:0,defects:new Map<string,number>(),reports:new Map<string,string>(),last:r.createdAt};g.occurrences++;if(r.critical)g.critical++;g.defects.set(r.defect,(g.defects.get(r.defect)||0)+1);if(!g.reports.has(r.defect))g.reports.set(r.defect,r.report);if(new Date(r.createdAt)>new Date(g.last))g.last=r.createdAt;groups.set(r.key,g)});
   const modelRows:IntelligenceRow[]=[...groups.values()].map(g=>{const top=[...g.defects.entries()].sort((a,b)=>b[1]-a[1])[0];return{key:g.key,productId:g.productId,name:g.name,model:g.model,sku:g.sku,brand:g.brand,occurrences:g.occurrences,critical:g.critical,topDefect:top?.[0]||'Defeito ainda não classificado',topDefectCount:top?.[1]||0,topReport:g.reports.get(top?.[0]||'')||'Sem relato técnico detalhado',last:g.last}}).sort((a,b)=>b.occurrences-a.occurrences);
   const defectMap=new Map<string,number>();records.forEach(r=>defectMap.set(r.defect,(defectMap.get(r.defect)||0)+1));
   const defectRows=[...defectMap.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,8);
   const monthMap=new Map<string,number>();records.forEach(r=>{const d=new Date(r.createdAt),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;monthMap.set(k,(monthMap.get(k)||0)+1)});
   const monthly=[...monthMap.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-12).map(([month,occurrences])=>({month:month.slice(5)+'/'+month.slice(2,4),occurrences}));
   const critical=records.filter(r=>r.critical).length,unclassified=records.filter(r=>r.defect==='Defeito ainda não classificado').length;
   return{records,modelRows,defectRows,monthly,total:records.length,critical,unclassified,topModel:modelRows[0],topDefect:defectRows[0]};
 },[tickets,products,period]);
 const visibleRows=useMemo(()=>{const q=normalize(intelQuery);return intelligence.modelRows.filter(r=>!q||[r.name,r.model,r.sku,r.topDefect,r.topReport].some(v=>normalize(v).includes(q)));},[intelligence.modelRows,intelQuery]);
 const openCreate=()=>{setDraft(empty);setEditing(null);setCreating(true);setError('');setMessage('')};
 const openEdit=(p:Product)=>{setCreating(false);setEditing(p);setDraft({name:p.name||'',codeSku:p.codeSku||'',description:p.description||'',model:p.model||'',brand:p.brand||'',anvisaRegister:p.anvisaRegister||'',supplierName:p.supplierName||'',manufacturerName:p.manufacturerName||'',importerName:p.importerName||'',distributorName:p.distributorName||'',countryOrigin:p.countryOrigin||''});setError('');setMessage('')};
 const close=()=>{setCreating(false);setEditing(null)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft.name.trim()||!draft.codeSku.trim()){setError('Nome e SKU são obrigatórios.');return}setBusy(true);setError('');try{if(creating)await productMasterService.create(draft as ProductCreateInput);else if(editing)await productMasterService.update(editing.id,draft as ProductMasterChanges);setMessage(creating?'Produto cadastrado e disponível para novos SACs.':'Produto atualizado com auditoria.');close();await load();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));await onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar produto.')}finally{setBusy(false)}};
 const toggle=async(p:Product)=>{if(!allowed)return;const active=p.isActive===false,action=active?'reativar':'inativar';if(!window.confirm(`Deseja ${action} ${p.name}?`))return;setBusy(true);try{await productMasterService.setActive(p.id,active);await load();window.dispatchEvent(new CustomEvent('sacproh:products-changed'));await onChanged?.()}catch(e){setError(e instanceof Error?e.message:`Falha ao ${action}.`)}finally{setBusy(false)}};
 const exportCsv=()=>{const rows=[['Posição','Produto','Modelo','SKU','Ocorrências','Críticas','Principal defeito','Relato real','Peso do defeito','Última ocorrência'],...visibleRows.map((r,i)=>[i+1,r.name,r.model,r.sku,r.occurrences,r.critical,r.topDefect,r.topReport,`${Math.round(r.topDefectCount/Math.max(1,r.occurrences)*100)}%`,new Date(r.last).toLocaleDateString('pt-BR')])];const csv=rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`sacproh-inteligencia-produtos-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
 const field=(key:keyof Draft,label:string,placeholder='')=><label className="text-xs font-bold text-slate-700">{label}<input value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={placeholder} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 font-normal outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-500"/></label>;
 return <div className="space-y-5 pb-8">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="w-7 h-7 text-[#145EDB]"/><h1 className="text-2xl font-extrabold text-[#10233F]">Ranking de Modelos por Ocorrências</h1></div><p className="text-sm text-slate-500 mt-1">Visão detalhada dos produtos com maior recorrência e dos defeitos efetivamente relatados nos SACs.</p></div><div className="flex items-center gap-2"><select value={period} onChange={e=>setPeriod(e.target.value as Period)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-bold shadow-sm"><option value="90">Últimos 90 dias</option><option value="365">Últimos 12 meses</option><option value="all">Todo o histórico</option></select><button onClick={exportCsv} className="rounded-xl border border-blue-200 bg-white px-4 py-2.5 text-xs font-extrabold text-[#145EDB] flex items-center gap-2 shadow-sm"><Download className="w-4 h-4"/>Exportar relatório</button>{allowed&&<button onClick={openCreate} className="rounded-xl bg-[#FF8500] text-white font-extrabold px-4 py-2.5 flex items-center gap-2 shadow-sm"><PackagePlus className="w-4 h-4"/>Cadastrar produto</button>}</div></div>
  <div className="inline-flex rounded-xl bg-slate-100 p-1 text-xs font-bold"><button onClick={()=>setTab('intelligence')} className={`px-4 py-2 rounded-lg ${tab==='intelligence'?'bg-white text-[#145EDB] shadow-sm':'text-slate-500'}`}>Inteligência de Produto</button><button onClick={()=>setTab('catalog')} className={`px-4 py-2 rounded-lg ${tab==='catalog'?'bg-white text-[#145EDB] shadow-sm':'text-slate-500'}`}>Catálogo Mestre</button></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 text-red-700 p-3 text-sm">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 text-emerald-700 p-3 text-sm">{message}</div>}
  {tab==='intelligence'?<>
   <div className="grid grid-cols-2 lg:grid-cols-5 gap-4"><Kpi icon={<BarChart3/>} label="Total de ocorrências" value={intelligence.total} note="Chamados relacionados" tone="blue"/><Kpi icon={<Package/>} label="Produtos envolvidos" value={intelligence.modelRows.length} note="Produtos/modelos consolidados" tone="green"/><Kpi icon={<AlertTriangle/>} label="Ocorrências críticas" value={intelligence.critical} note={intelligence.total?`${Math.round(intelligence.critical/intelligence.total*100)}% do total`:'Sem ocorrências'} tone="orange"/><Kpi icon={<Target/>} label="Principal defeito" value={intelligence.topDefect?.name||'-'} note={intelligence.topDefect?`${intelligence.topDefect.value} ocorrência(s)`:'Sem classificação'} tone="red" compact/><Kpi icon={<CalendarDays/>} label="Período analisado" value={period==='90'?'90 dias':period==='365'?'12 meses':'Histórico'} note="Filtro aplicado" tone="purple" compact/></div>
   {intelligence.unclassified>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 flex gap-2"><ShieldAlert className="w-4 h-4 shrink-0"/><span><b>{intelligence.unclassified} ocorrência(s)</b> ainda não possuem modo de falha identificável no relato. Elas permanecem como “Defeito ainda não classificado” para saneamento, sem inventar informação.</span></div>}
   <div className="grid xl:grid-cols-[1fr_340px] gap-4">
    <section className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"><div className="p-4 border-b flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-extrabold text-[#10233F]">Ranking detalhado por produto / modelo</h3><p className="text-xs text-slate-500">O SKU é secundário. O agrupamento prioriza o cadastro mestre e consolida registros históricos equivalentes.</p></div><div className="flex items-center gap-2"><div className="relative"><Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400"/><input value={intelQuery} onChange={e=>setIntelQuery(e.target.value)} placeholder="Buscar produto ou defeito..." className="pl-9 pr-3 py-2 rounded-lg border border-slate-200 text-xs w-64"/></div><button className="border rounded-lg px-3 py-2 text-xs font-bold flex gap-1"><Filter className="w-4 h-4"/>Filtros</button></div></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500 uppercase"><tr><th className="text-center p-3 w-16">Posição</th><th className="text-left p-3">Produto / Modelo</th><th className="text-center p-3">Ocorrências</th><th className="text-center p-3">Críticas</th><th className="text-left p-3">Principal defeito</th><th className="text-left p-3">Relato real</th><th className="text-center p-3">Peso</th><th className="text-left p-3">Última</th></tr></thead><tbody className="divide-y divide-slate-100">{visibleRows.map((r,i)=><tr key={r.key} className="hover:bg-slate-50"><td className="p-3 text-center"><Rank n={i+1}/></td><td className="p-3"><div className="flex items-center gap-3"><ProductThumb name={r.name+' '+r.model}/><div><div className="font-bold text-[#10233F] text-sm">{productLabel(r.name,r.model)}</div><div className="text-[10px] text-slate-400 mt-1">{r.brand||'Marca não informada'}{r.sku?` · SKU ${r.sku}`:''}</div></div></div></td><td className="p-3 text-center"><b className="text-[#145EDB] text-base">{r.occurrences}</b><div className="text-[10px] text-slate-400">{intelligence.total?`${(r.occurrences/intelligence.total*100).toFixed(1)}% do total`:''}</div></td><td className="p-3 text-center"><b className={r.critical?'text-red-600':'text-slate-400'}>{r.critical}</b></td><td className="p-3 min-w-48"><div className="font-bold text-slate-800">{r.topDefect}</div></td><td className="p-3 min-w-64 max-w-sm"><div className="text-slate-600 leading-relaxed">{r.topReport}</div></td><td className="p-3 text-center"><div className="font-bold">{Math.round(r.topDefectCount/Math.max(1,r.occurrences)*100)}%</div><div className="w-20 h-1.5 bg-slate-100 rounded-full overflow-hidden mx-auto mt-1"><div className="h-full rounded-full bg-[#ef4444]" style={{width:`${Math.round(r.topDefectCount/Math.max(1,r.occurrences)*100)}%`}}/></div></td><td className="p-3 whitespace-nowrap text-slate-600">{new Date(r.last).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div></section>
    <div className="space-y-4"><ChartCard title="Principais defeitos" subtitle="Modos de falha identificados nos relatos"><ResponsiveContainer width="100%" height={285}><PieChart><Pie data={intelligence.defectRows} dataKey="value" nameKey="name" innerRadius={48} outerRadius={88} paddingAngle={2}>{intelligence.defectRows.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/><Legend wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Tendência de ocorrências" subtitle="Evolução mensal"><ResponsiveContainer width="100%" height={220}><LineChart data={intelligence.monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis allowDecimals={false} tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey="occurrences" stroke="#145EDB" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></ChartCard><QualityInsight rows={intelligence.modelRows} total={intelligence.total}/></div>
   </div>
   <div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Produtos com mais ocorrências" subtitle="Top 8 por produto/modelo"><ResponsiveContainer width="100%" height={300}><BarChart data={intelligence.modelRows.slice(0,8).map(r=>({...r,label:productLabel(r.name,r.model)}))} layout="vertical" margin={{left:25,right:20}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="label" width={165} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="occurrences" fill="#145EDB" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></ChartCard><div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-violet-50 to-white p-5"><div className="flex items-center gap-2 text-violet-700"><TrendingUp className="w-5 h-5"/><h3 className="font-extrabold">Leitura inteligente</h3></div><div className="mt-4 space-y-3 text-sm"><InsightLine icon={<Wrench/>} title="Produto prioritário" value={intelligence.topModel?`${productLabel(intelligence.topModel.name,intelligence.topModel.model)} · ${intelligence.topModel.occurrences} ocorrência(s)`:'Sem dados'}/><InsightLine icon={<Target/>} title="Falha predominante" value={intelligence.topDefect?`${intelligence.topDefect.name} · ${intelligence.topDefect.value} ocorrência(s)`:'Sem dados'}/><InsightLine icon={<AlertTriangle/>} title="Criticidade" value={`${intelligence.critical} ocorrência(s) crítica(s) no período`}/></div><p className="text-xs text-violet-700 mt-4">Priorize investigação conjunta de produto, lote, fornecedor/fabricante, causa raiz e plano CAPA nos itens que concentram recorrência e repetição do mesmo modo de falha.</p></div></div>
  </>:<>
   <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><MiniStat label="Produtos cadastrados" value={stats.total}/><MiniStat label="Ativos" value={stats.active}/><MiniStat label="Sem ANVISA" value={stats.noAnvisa}/><MiniStat label="Sem descrição" value={stats.noDescription}/></div>
   <div className="bg-white rounded-xl border border-slate-200 p-3 flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por produto, modelo, SKU, marca ou ANVISA" className="w-full pl-9 pr-3 py-2 rounded-lg border border-slate-200 text-sm"/></div><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/>Mostrar inativos</label></div>
   <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(p=><div key={p.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-3"><ProductThumb name={p.name+' '+(p.model||'')} large/><div className="min-w-0"><h3 className="font-extrabold text-[#10233F]">{productLabel(p.name,p.model||'')}</h3><p className="text-[10px] text-slate-400 mt-1">SKU {p.codeSku}{p.brand?` · ${p.brand}`:''}</p><p className="text-xs text-slate-600 mt-2 line-clamp-2">{p.description||'Descrição técnica não informada.'}</p></div></div><div className="flex gap-2 mt-4">{allowed&&<button onClick={()=>openEdit(p)} className="flex-1 rounded-lg border px-3 py-2 text-xs font-bold flex justify-center gap-1"><Edit3 className="w-3.5 h-3.5"/>Editar</button>}{allowed&&<button onClick={()=>toggle(p)} className="rounded-lg border px-3 py-2"><Power className={`w-4 h-4 ${p.isActive===false?'text-slate-400':'text-emerald-600'}`}/></button>}</div></div>)}</div>
  </>}
  {(creating||editing)&&<div className="fixed inset-0 z-[100] bg-black/40 flex items-center justify-center p-4"><form onSubmit={save} className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[90vh] overflow-auto"><div className="p-5 border-b flex justify-between"><div><h2 className="font-extrabold text-lg">{creating?'Cadastrar novo produto':'Editar produto'}</h2><p className="text-xs text-slate-500">Cadastro mestre utilizado em todos os SACs.</p></div><button type="button" onClick={close}><X/></button></div><div className="p-5 grid md:grid-cols-2 gap-4">{field('name','Nome oficial *','Ex.: Cadeira de Transferência PRO900')}{field('codeSku','SKU / código *','Ex.: 1156')}{field('model','Modelo','Ex.: PRO900')}{field('brand','Marca')}{field('anvisaRegister','Registro ANVISA')}{field('manufacturerName','Fabricante')}{field('supplierName','Fornecedor')}{field('importerName','Importador')}{field('distributorName','Distribuidor')}{field('countryOrigin','País de origem')}<label className="md:col-span-2 text-xs font-bold text-slate-700">Descrição técnica<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} rows={4} className="mt-1 w-full rounded-lg border border-slate-200 p-3 font-normal"/></label></div><div className="p-5 border-t flex justify-end gap-2"><button type="button" onClick={close} className="px-4 py-2 rounded-lg border font-bold text-sm">Cancelar</button><button disabled={busy} className="px-5 py-2 rounded-lg bg-[#145EDB] text-white font-extrabold text-sm">{busy?'Salvando...':'Salvar produto'}</button></div></form></div>}
 </div>;
};

const ProductThumb=({name,large=false}:{name:string;large?:boolean})=>{const n=normalize(name);const Icon=n.includes('cama')?BedDouble:n.includes('cadeira')?Armchair:n.includes('bike')||n.includes('bicic')?Bike:n.includes('motor')||n.includes('bomba')?Cog:Package;return <div className={`${large?'w-16 h-16':'w-12 h-12'} shrink-0 rounded-xl bg-gradient-to-br from-slate-50 to-blue-50 border border-slate-200 flex items-center justify-center`}><Icon className={`${large?'w-9 h-9':'w-7 h-7'} text-[#315b7d]`}/></div>};
const Rank=({n}:{n:number})=>n<=3?<span className={`inline-flex w-8 h-8 rounded-full items-center justify-center font-extrabold text-white ${n===1?'bg-amber-500':n===2?'bg-slate-400':'bg-orange-600'}`}>{n}</span>:<span className="inline-flex w-8 h-8 rounded-full items-center justify-center font-bold bg-slate-100 text-slate-600">{n}</span>;
const Kpi=({icon,label,value,note,tone,compact=false}:{icon:React.ReactNode;label:string;value:string|number;note:string;tone:'blue'|'green'|'orange'|'red'|'purple';compact?:boolean})=>{const c={blue:'text-blue-600 bg-blue-50',green:'text-emerald-600 bg-emerald-50',orange:'text-orange-600 bg-orange-50',red:'text-red-500 bg-red-50',purple:'text-violet-600 bg-violet-50'}[tone];return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><div className={`w-11 h-11 rounded-full flex items-center justify-center [&>svg]:w-5 [&>svg]:h-5 ${c}`}>{icon}</div><div className="min-w-0"><div className="text-[10px] font-extrabold text-slate-500 uppercase">{label}</div><div className={`${compact?'text-base leading-tight':'text-3xl'} font-extrabold mt-1 text-[#10233F] break-words`}>{value}</div><div className="text-[10px] text-slate-500 mt-1">{note}</div></div></div></div>};
const MiniStat=({label,value}:{label:string;value:number})=><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-2xl font-extrabold text-[#145EDB]">{value}</div><div className="text-[10px] uppercase font-bold text-slate-500 mt-1">{label}</div></div>;
const ChartCard=({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode})=><section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-extrabold text-[#10233F]">{title}</h3><p className="text-[10px] text-slate-500 mb-3">{subtitle}</p>{children}</section>;
const InsightLine=({icon,title,value}:{icon:React.ReactNode;title:string;value:string})=><div className="flex gap-3"><div className="w-9 h-9 rounded-full bg-white shadow-sm flex items-center justify-center text-violet-600 [&>svg]:w-4 [&>svg]:h-4">{icon}</div><div><div className="text-[10px] uppercase font-bold text-slate-500">{title}</div><div className="font-extrabold text-slate-800">{value}</div></div></div>;
const QualityInsight=({rows,total}:{rows:IntelligenceRow[];total:number})=>{const top=rows.slice(0,3).reduce((s,r)=>s+r.occurrences,0),pct=total?Math.round(top/total*100):0;return <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 text-violet-700"><TrendingUp className="w-5 h-5"/><b>Insight de Qualidade</b></div><p className="text-xs font-bold text-slate-800 mt-3">Os 3 primeiros produtos concentram {pct}% das ocorrências do período.</p><p className="text-xs text-slate-600 mt-2">Recomendação: revisar causa raiz, lotes, fabricante, assistência técnica e CAPA nos itens de maior concentração.</p></div>};
