import { supabase } from '../lib/supabase';

export type ProductFamily={id:string;name:string;code?:string};
export type ProductMasterRecord={
 id:string;tenantId:string;familyId?:string;familyName?:string;codeSku:string;name:string;description?:string;model?:string;brand?:string;anvisaRegister?:string;supplierName?:string;manufacturerName?:string;importerName?:string;distributorName?:string;countryOrigin?:string;imageUrl?:string;isActive:boolean;
 gtinEan?:string;ncm?:string;unitMeasure?:string;manufacturerReference?:string;regulatoryType?:string;anvisaStatus?:string;anvisaExpirationDate?:string;anvisaRiskClass?:string;inmetroRegister?:string;inmetroExpirationDate?:string;udiDi?:string;lotControl:boolean;serialControl:boolean;expirationControl:boolean;shelfLifeMonths?:number;warrantyMonths?:number;intendedUse?:string;technicalSpecifications?:string;storageConditions?:string;handlingNotes?:string;accessoriesIncluded?:string;updatedAt?:string;
};
export type ProductMasterForm=Omit<ProductMasterRecord,'id'|'tenantId'|'familyName'|'isActive'|'updatedAt'>;
const map=(r:any,families:Record<string,string>):ProductMasterRecord=>({id:r.id,tenantId:r.tenant_id,familyId:r.family_id||undefined,familyName:r.family_id?families[String(r.family_id)]:undefined,codeSku:r.code_sku,name:r.name,description:r.description||undefined,model:r.model||undefined,brand:r.brand||undefined,anvisaRegister:r.anvisa_register||undefined,supplierName:r.supplier_name||undefined,manufacturerName:r.manufacturer_name||undefined,importerName:r.importer_name||undefined,distributorName:r.distributor_name||undefined,countryOrigin:r.country_origin||undefined,imageUrl:r.image_url||undefined,isActive:r.is_active!==false,gtinEan:r.gtin_ean||undefined,ncm:r.ncm||undefined,unitMeasure:r.unit_measure||undefined,manufacturerReference:r.manufacturer_reference||undefined,regulatoryType:r.regulatory_type||undefined,anvisaStatus:r.anvisa_status||undefined,anvisaExpirationDate:r.anvisa_expiration_date||undefined,anvisaRiskClass:r.anvisa_risk_class||undefined,inmetroRegister:r.inmetro_register||undefined,inmetroExpirationDate:r.inmetro_expiration_date||undefined,udiDi:r.udi_di||undefined,lotControl:r.lot_control!==false,serialControl:Boolean(r.serial_control),expirationControl:Boolean(r.expiration_control),shelfLifeMonths:r.shelf_life_months==null?undefined:Number(r.shelf_life_months),warrantyMonths:r.warranty_months==null?undefined:Number(r.warranty_months),intendedUse:r.intended_use||undefined,technicalSpecifications:r.technical_specifications||undefined,storageConditions:r.storage_conditions||undefined,handlingNotes:r.handling_notes||undefined,accessoriesIncluded:r.accessories_included||undefined,updatedAt:r.updated_at||undefined});
export const productMasterAdvancedService={
 async listFamilies():Promise<ProductFamily[]>{const {data,error}=await supabase.from('product_families').select('id,name,code').order('name');if(error)throw new Error(`Não foi possível carregar famílias: ${error.message}`);return (data||[]).map((r:any)=>({id:r.id,name:r.name,code:r.code||undefined}));},
 async createFamily(name:string,code?:string):Promise<ProductFamily>{const {data,error}=await supabase.rpc('create_product_family',{p_name:name,p_code:code||null});if(error||!data)throw new Error(`Não foi possível criar a família: ${error?.message||''}`);return {id:data.id,name:data.name,code:data.code||undefined};},
 async list():Promise<ProductMasterRecord[]>{const [familiesResult,productsResult]=await Promise.all([supabase.from('product_families').select('id,name'),supabase.from('products').select('*').order('is_active',{ascending:false}).order('name')]);if(familiesResult.error)throw new Error(`Não foi possível carregar famílias: ${familiesResult.error.message}`);if(productsResult.error)throw new Error(`Não foi possível carregar produtos: ${productsResult.error.message}`);const families:Record<string,string>={};for(const r of (familiesResult.data||[]) as any[])families[String(r.id)]=String(r.name);return (productsResult.data||[]).map((r:any)=>map(r,families));},
 async create(input:ProductMasterForm):Promise<void>{const {error}=await supabase.rpc('create_product_master',{p_product:input});if(error)throw new Error(`Não foi possível cadastrar o produto: ${error.message}`);},
 async update(id:string,input:ProductMasterForm):Promise<void>{const {error}=await supabase.rpc('update_product_master',{p_product_id:id,p_changes:input});if(error)throw new Error(`Não foi possível atualizar o produto: ${error.message}`);},
 async setActive(id:string,active:boolean):Promise<void>{const {error}=await supabase.rpc('set_product_master_active',{p_product_id:id,p_active:active});if(error)throw new Error(`Não foi possível ${active?'reativar':'inativar'} o produto: ${error.message}`);}
};