import { supabase } from '../lib/supabase';

export type ProductCompliance={productId:string;tenantId:string;udiDi?:string;anvisaRegistration?:string;anvisaExpiration?:string;inmetroRequired:boolean;inmetroRegistration?:string;certificateNumber?:string;certificateExpiration?:string;certificationBody?:string;applicableStandard?:string;notes?:string};
const map=(row:any):ProductCompliance=>({productId:row.product_id,tenantId:row.tenant_id,udiDi:row.udi_di||'',anvisaRegistration:row.anvisa_registration||'',anvisaExpiration:row.anvisa_expiration||'',inmetroRequired:Boolean(row.inmetro_required),inmetroRegistration:row.inmetro_registration||'',certificateNumber:row.certificate_number||'',certificateExpiration:row.certificate_expiration||'',certificationBody:row.certification_body||'',applicableStandard:row.applicable_standard||'',notes:row.notes||''});
export const regulatoryService={
  async listCompliance(){const{data,error}=await supabase.from('product_regulatory_compliance').select('*').order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(map);},
  async saveCompliance(item:ProductCompliance,userId:string){const{data,error}=await supabase.from('product_regulatory_compliance').upsert({product_id:item.productId,tenant_id:item.tenantId,udi_di:item.udiDi||null,anvisa_registration:item.anvisaRegistration||null,anvisa_expiration:item.anvisaExpiration||null,inmetro_required:item.inmetroRequired,inmetro_registration:item.inmetroRegistration||null,certificate_number:item.certificateNumber||null,certificate_expiration:item.certificateExpiration||null,certification_body:item.certificationBody||null,applicable_standard:item.applicableStandard||null,notes:item.notes||null,updated_by:userId,updated_at:new Date().toISOString()},{onConflict:'product_id'}).select().single();if(error)throw error;return map(data);},
  async saveSnapshot(input:{tenantId:string;type:'ANVISA'|'INMETRO';start:string;end:string;title:string;summary:unknown;userId:string}){const{error}=await supabase.from('regulatory_report_snapshots').insert({tenant_id:input.tenantId,report_type:input.type,period_start:input.start,period_end:input.end,title:input.title,summary:input.summary,created_by:input.userId});if(error)throw error;}
};
