import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, Check, LoaderCircle, LogIn } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { CommercialAlert, commercialTrialService } from '../../services/commercialTrialService';

export function CommercialAlertsAdmin(){
  const [authenticated,setAuthenticated]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const [alerts,setAlerts]=useState<CommercialAlert[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setAlerts(await commercialTrialService.listAlerts());}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar alertas.');}finally{setLoading(false);}};
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setAuthenticated(true);load();}});},[]);
  const login=async(event:FormEvent)=>{event.preventDefault();setLoading(true);const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError){setError('E-mail ou senha inválidos.');setLoading(false);return;}setAuthenticated(true);await load();};
  const acknowledge=async(id:string)=>{setLoading(true);try{await commercialTrialService.acknowledgeAlert(id);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao reconhecer alerta.');setLoading(false);}};
  const field='mt-3 w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white';
  if(!authenticated)return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-slate-900 p-8"><AlertTriangle className="text-amber-300"/><h1 className="mt-4 text-2xl font-black">Alertas financeiros</h1><input required type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} className={field}/><input required type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} className={field}/><button disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-300 p-3 font-black text-slate-950"><LogIn size={18}/>Entrar</button>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}</form></main>;
  return <main className="min-h-screen bg-slate-950 p-5 text-white"><div className="mx-auto max-w-4xl py-10"><a href="/commercial-orders" className="flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Voltar aos pedidos</a><header className="mt-5"><h1 className="text-3xl font-black">Alertas financeiros</h1><p className="mt-2 text-sm text-slate-400">Divergências, rejeições, cancelamentos, estornos e chargebacks pendentes.</p></header>{loading&&<p className="mt-5 flex gap-2 text-cyan-300"><LoaderCircle className="animate-spin" size={18}/>Atualizando...</p>}{error&&<p className="mt-5 rounded-xl bg-red-400/10 p-3 text-red-300">{error}</p>}<div className="mt-7 grid gap-4">{alerts.map(alert=><article key={alert.id} className={`rounded-2xl border p-5 ${alert.severity==='CRITICAL'?'border-red-400/30 bg-red-400/10':'border-amber-300/30 bg-amber-300/10'}`}><div className="flex items-start justify-between gap-4"><div><strong>{alert.alert_type}</strong><p className="mt-2 text-sm text-slate-200">{alert.message}</p><p className="mt-2 text-xs text-slate-400">{new Date(alert.created_at).toLocaleString('pt-BR')}</p></div><button onClick={()=>acknowledge(alert.id)} disabled={loading} className="flex shrink-0 items-center gap-2 rounded-xl border border-white/20 px-3 py-2 text-sm"><Check size={16}/>Reconhecer</button></div></article>)}{!loading&&!alerts.length&&<p className="rounded-2xl border border-emerald-300/20 bg-emerald-300/10 p-5 text-emerald-300">Nenhum alerta financeiro aberto.</p>}</div></div></main>;
}
