import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, Clipboard, CreditCard, LoaderCircle, LogIn } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { CommercialTrial, commercialTrialService } from '../../services/commercialTrialService';

export function CommercialOrderAdmin() {
  const [authenticated,setAuthenticated]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
  const [trials,setTrials]=useState<CommercialTrial[]>([]),[trialId,setTrialId]=useState(''),[evidence,setEvidence]=useState(''),[version,setVersion]=useState('');
  const [paymentLink,setPaymentLink]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async()=>{const rows=await commercialTrialService.list();setTrials(rows.filter(row=>Boolean(row.provisioned_tenant_id)&&['TRIAL_ACTIVE','TRIAL_REVIEW','WON'].includes(row.status)));};
  useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(data.session){setAuthenticated(true);try{await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.');}}});},[]);
  const login=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError('');const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError){setError('E-mail ou senha inválidos.');setLoading(false);return;}setAuthenticated(true);try{await load();}catch(e){setError(e instanceof Error?e.message:'Acesso comercial não autorizado.');}finally{setLoading(false);}};
  const prepare=async(event:FormEvent)=>{event.preventDefault();if(!window.confirm('Confirma que a referência informada corresponde ao contrato aceito pelo cliente?'))return;setLoading(true);setError('');setPaymentLink('');try{const result=await commercialTrialService.prepareOrder(trialId,evidence,version);setPaymentLink(result.paymentLink);}catch(e){setError(e instanceof Error?e.message:'Não foi possível preparar o pedido.');}finally{setLoading(false);}};
  const field='mt-1.5 w-full rounded-xl border border-white/15 bg-slate-950 p-3 text-white outline-none focus:border-cyan-300';

  if(!authenticated)return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-slate-900 p-8"><CreditCard className="text-cyan-300"/><h1 className="mt-4 text-2xl font-black">Pedidos anuais</h1><p className="mt-2 text-sm text-slate-400">Acesso exclusivo para operadores comerciais autorizados.</p><input required type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} className={field}/><input required type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} className={field}/><button disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-300 p-3 font-black text-slate-950"><LogIn size={18}/>Entrar</button>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}</form></main>;

  return <main className="min-h-screen bg-slate-950 p-5 text-white"><div className="mx-auto max-w-2xl py-10"><a href="/commercial-trials" className="flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/>Voltar ao funil</a><div className="mt-6 rounded-3xl border border-white/10 bg-slate-900 p-7"><CreditCard className="text-cyan-300"/><h1 className="mt-4 text-3xl font-black">Preparar pedido anual</h1><p className="mt-2 text-sm text-slate-400">Gere o link somente depois de confirmar a evidência do contrato aceito.</p><form onSubmit={prepare} className="mt-7 grid gap-4"><label className="text-sm font-bold">Trial provisionado<select required value={trialId} onChange={e=>setTrialId(e.target.value)} className={field}><option value="">Selecione</option>{trials.map(trial=><option key={trial.id} value={trial.id}>{trial.company_name} · {trial.plan_interest} · {trial.work_email}</option>)}</select></label><label className="text-sm font-bold">Referência da evidência contratual<input required maxLength={300} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Ex.: contrato DOC-2026-001 assinado" className={field}/></label><label className="text-sm font-bold">Versão do contrato<input required maxLength={80} value={version} onChange={e=>setVersion(e.target.value)} placeholder="Ex.: SAC4-2026.1" className={field}/></label><button disabled={loading} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-emerald-300 p-3 font-black text-slate-950">{loading?<LoaderCircle className="animate-spin" size={18}/>:<CreditCard size={18}/>}Gerar link conciliado</button></form>{error&&<p className="mt-4 rounded-xl bg-red-400/10 p-3 text-sm text-red-300">{error}</p>}{paymentLink&&<div className="mt-5 rounded-xl bg-emerald-400/10 p-4"><strong className="text-emerald-300">Link pronto para o cliente</strong><p className="mt-2 break-all text-xs text-slate-300">{paymentLink}</p><button onClick={()=>navigator.clipboard.writeText(paymentLink)} className="mt-3 flex items-center gap-2 rounded-lg border border-emerald-300/30 px-3 py-2 text-sm"><Clipboard size={16}/>Copiar link</button></div>}</div></div></main>;
}
