import {FormEvent,useEffect,useMemo,useState} from 'react';
import {BarChart3,ExternalLink,LoaderCircle,ShieldCheck,TrendingUp,Users} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import {listMarketingEvents} from '../../services/marketingAnalytics';
import type {MarketingEvent} from '../../services/marketingAnalytics';

export function MarketingAnalyticsAdmin(){
  const [authenticated,setAuthenticated]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[items,setItems]=useState<MarketingEvent[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setItems(await listMarketingEvents(30));}catch{setError('Não foi possível carregar as métricas. Aplique a migration de marketing no Supabase.');}finally{setLoading(false);}};
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setAuthenticated(true);load();}});},[]);
  const login=async(e:FormEvent)=>{e.preventDefault();setLoading(true);const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError){setError('E-mail ou senha inválidos.');setLoading(false);return;}setAuthenticated(true);await load();};
  const stats=useMemo(()=>({views:items.filter(x=>x.event_name==='page_view').length,leads:items.filter(x=>x.event_name==='trial_submit_success').length,ctas:items.filter(x=>x.event_name.startsWith('cta_')).length,sources:(Object.entries(items.reduce<Record<string,number>>((a,x)=>{const k=x.source||'Direto';a[k]=(a[k]||0)+1;return a;},{})) as [string,number][]).sort((a,b)=>b[1]-a[1]).slice(0,6)}),[items]);
  if(!authenticated)return <main className="grid min-h-screen place-items-center bg-slate-950 p-5 text-white"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-slate-900 p-8"><ShieldCheck className="text-orange-300"/><h1 className="mt-4 text-2xl font-black">Marketing e Analytics</h1><input type="email" required placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} className="mt-6 w-full rounded-xl bg-slate-950 p-3"/><input type="password" required placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} className="mt-3 w-full rounded-xl bg-slate-950 p-3"/><button className="mt-4 w-full rounded-xl bg-[#FF8500] p-3 font-bold">Entrar</button>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</form></main>;
  return <main className="min-h-screen bg-slate-950 p-5 text-white md:p-10"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-orange-300">GRIT • últimos 30 dias</p><h1 className="text-3xl font-black">Dashboard de marketing</h1></div><button onClick={load} className="rounded-xl border border-white/15 px-4 py-2">{loading?<LoaderCircle className="animate-spin"/>:'Atualizar'}</button></div>{error&&<p className="mt-4 rounded-xl bg-red-400/10 p-3 text-red-300">{error}</p>}<div className="mt-8 grid gap-4 md:grid-cols-3">{[[Users,'Visitas',stats.views],[TrendingUp,'Conversões de trial',stats.leads],[BarChart3,'Cliques em CTAs',stats.ctas]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-white/10 bg-slate-900 p-6"><Icon className="text-orange-300"/><p className="mt-4 text-sm text-slate-400">{label}</p><strong className="text-4xl">{value}</strong></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="font-black">Origem das visitas e ações</h2><div className="mt-5 space-y-3">{stats.sources.map(([name,value])=><div key={name} className="flex justify-between border-b border-white/10 pb-2"><span>{name}</span><strong>{value}</strong></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-slate-900 p-6"><h2 className="font-black">Próximas ações recomendadas</h2><ul className="mt-5 space-y-3 text-sm text-slate-300"><li>• Use UTMs diferentes em Instagram, Google e WhatsApp.</li><li>• Priorize campanhas com mais conversões de trial, não apenas visitas.</li><li>• Publique demonstrações do SAC 4.0 e casos de uso por segmento.</li><li>• Revise semanalmente origem, CTA e taxa de conversão.</li></ul><a href="https://analytics.google.com/" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-orange-300">Abrir Google Analytics <ExternalLink size={16}/></a></section></div></div></main>;
}
