import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock, Download, FileSpreadsheet, Filter, PackageSearch, Printer, RefreshCw, TrendingUp, WalletCards, ClipboardList } from 'lucide-react';
import type { Tenant, Ticket, UserProfile } from '../../types';
import { supabase } from '../../lib/supabase';

interface ExecutiveDashboardProps { tickets: Ticket[]; tenant: Tenant; currentUser?: UserProfile | null; }
type ManagementRow = { ticket_id:string; protocol:string; status:string; priority:string; category:string; customer_name:string; assigned_to_name?:string; assigned_area?:string; created_at:string; sla_due_at?:string; open_actions:number; overdue_actions:number; next_due_at?:string; gross_cost:number; recovered_amount:number; net_cost:number; cost_entries:number };
const CLOSED = new Set(['CLOSED_PROCEDENT','CLOSED_NON_PROCEDENT','CANCELLED']);
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const download=(name:string,content:string,type:string)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};

export const ExecutiveDashboard:React.FC<ExecutiveDashboardProps>=({tickets,tenant,currentUser})=>{
 const [period,setPeriod]=useState<'30'|'90'|'365'|'ALL'>('ALL'); const [status,setStatus]=useState('ALL'); const [priority,setPriority]=useState('ALL'); const [category,setCategory]=useState('ALL'); const [productQuery,setProductQuery]=useState('');
 const [management,setManagement]=useState<ManagementRow[]>([]); const [managementError,setManagementError]=useState(''); const [loadingManagement,setLoadingManagement]=useState(false);
 const loadManagement=async()=>{setLoadingManagement(true);setManagementError('');const {data,error}=await supabase.from('sac_management_overview').select('*').eq('tenant_id',tenant.id);if(error)setManagementError(error.message);else setManagement((data||[]).map((r:any)=>({...r,open_actions:Number(r.open_actions||0),overdue_actions:Number(r.overdue_actions||0),gross_cost:Number(r.gross_cost||0),recovered_amount:Number(r.recovered_amount||0),net_cost:Number(r.net_cost||0),cost_entries:Number(r.cost_entries||0)})));setLoadingManagement(false)};
 useEffect(()=>{void loadManagement()},[tenant.id,tickets.length]);
 const filtered=useMemo(()=>{const limit=period==='ALL'?null:Date.now()-Number(period)*86400000;const q=productQuery.trim().toLocaleLowerCase('pt-BR');return tickets.filter(t=>(!limit||new Date(t.createdAt).getTime()>=limit)&&(status==='ALL'||t.status===status)&&(priority==='ALL'||t.priority===priority)&&(category==='ALL'||t.category===category)&&(!q||(t.items||[]).some(i=>[i.productName,i.productModel,i.productDescription,i.sku,i.lotNumber,i.serialNumber].some(v=>v?.toLocaleLowerCase('pt-BR').includes(q)))));},[tickets,period,status,priority,category,productQuery]);
 const categories=useMemo(()=>[...new Set(tickets.map(t=>t.category).filter(Boolean))].sort(),[tickets]);
 const metrics=useMemo(()=>{const closed=filtered.filter(t=>CLOSED.has(t.status));return{total:filtered.length,closed:closed.length,open:filtered.length-closed.length,critical:filtered.filter(t=>t.priority==='CRITICAL'||t.userRiskFlag||t.adverseEventFlag).length,overdue:filtered.filter(t=>!CLOSED.has(t.status)&&t.slaDueAt&&new Date(t.slaDueAt)<new Date()).length,averageDays:closed.length?closed.reduce((s,t)=>s+Math.max(0,(new Date(t.closedAt||t.updatedAt).getTime()-new Date(t.createdAt).getTime())/86400000),0)/closed.length:0};},[filtered]);
 const command=useMemo(()=>{const openRows=management.filter(r=>!CLOSED.has(r.status));const gross=management.reduce((s,r)=>s+r.gross_cost,0);const recovered=management.reduce((s,r)=>s+r.recovered_amount,0);return{actions:management.reduce((s,r)=>s+r.open_actions,0),overdueActions:management.reduce((s,r)=>s+r.overdue_actions,0),gross,recovered,net:gross-recovered,critical:openRows.filter(r=>r.priority==='CRITICAL').length,next:openRows.filter(r=>r.next_due_at).sort((a,b)=>new Date(a.next_due_at!).getTime()-new Date(b.next_due_at!).getTime()).slice(0,12)}},[management]);
 const quality=useMemo(()=>{const rows=filtered.flatMap(t=>(t.items||[]).map(item=>({t,item})));const okD=rows.filter(x=>x.item.productDescription?.trim()).length,okM=rows.filter(x=>x.item.productModel?.trim()).length,okT=rows.filter(x=>x.item.lotNumber?.trim()||x.item.serialNumber?.trim()).length;return{total:rows.length,description:rows.length?okD/rows.length*100:100,model:rows.length?okM/rows.length*100:100,trace:rows.length?okT/rows.length*100:100,incomplete:rows.filter(x=>!x.item.productDescription?.trim()||!x.item.productModel?.trim()||(!x.item.lotNumber?.trim()&&!x.item.serialNumber?.trim()))};},[filtered]);
 const ranking=(key:(t:Ticket)=>string)=>Object.entries(filtered.reduce<Record<string,number>>((a,t)=>{const k=key(t)||'Não classificado';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,8) as Array<[string,number]>;
 const topCategories=useMemo(()=>ranking(t=>t.category),[filtered]); const recurring=useMemo(()=>ranking(t=>t.customerName).filter(([,n])=>n>1),[filtered]);
 const topProducts=useMemo(()=>Object.entries(filtered.flatMap(t=>t.items||[]).reduce<Record<string,number>>((a,i)=>{const k=[i.productName,i.productModel].filter(Boolean).join(' · ')||'Não identificado';a[k]=(a[k]||0)+Number(i.quantity||1);return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,8) as Array<[string,number]>,[filtered]);
 const rows=()=>filtered.flatMap(t=>(t.items?.length?t.items:[undefined]).map(i=>({Protocolo:t.protocol,Abertura:new Date(t.createdAt).toLocaleString('pt-BR'),Status:t.status,Prioridade:t.priority,Categoria:t.category,Cliente:t.customerName,Responsavel:t.assignedToName||t.assignedArea||'',DescricaoOcorrencia:t.description,Produto:i?.productName||'',DescricaoProduto:i?.productDescription||'',Modelo:i?.productModel||'',SKU:i?.sku||'',Quantidade:i?.quantity||'',Lote:i?.lotNumber||'',Serie:i?.serialNumber||'',ANVISA:i?.anvisaRegister||'',Fabricante:i?.manufacturerName||'',SLA:t.slaDueAt?new Date(t.slaDueAt).toLocaleString('pt-BR'):''})));
 const exportCsv=()=>{const data=rows();if(!data.length)return;const headers=Object.keys(data[0]);download(`sacproh-final-${new Date().toISOString().slice(0,10)}.csv`,'\uFEFF'+[headers.map(csvCell).join(';'),...data.map(r=>headers.map(h=>csvCell((r as any)[h])).join(';'))].join('\n'),'text/csv;charset=utf-8')};
 const exportXlsx=async()=>{const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['SACPROH V4.9 - Relatório Final'],['Empresa',tenant.tradeName||tenant.name],['Emitido por',currentUser?.fullName||'Usuário'],['Emitido em',new Date().toLocaleString('pt-BR')],['SACs',metrics.total],['Em andamento',metrics.open],['Críticos',metrics.critical],['SLA vencido',metrics.overdue],['Pendências abertas',command.actions],['Pendências vencidas',command.overdueActions],['Custo bruto',command.gross],['Recuperado',command.recovered],['Custo líquido',command.net]]),'Resumo');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows()),'Protocolos');XLSX.writeFile(wb,`sacproh-final-${new Date().toISOString().slice(0,10)}.xlsx`)};
 return <div className="space-y-5">
  <section className="rounded-2xl bg-[#0B2343] text-white p-5 shadow-sm"><div className="flex flex-col lg:flex-row justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.18em] font-black text-blue-200">SACPROH V4.9 · Versão de produção</p><h1 className="text-2xl font-black">Central de comando do SAC</h1><p className="text-xs text-blue-100 mt-1">Protocolos, prazos, pendências, custos, produto e rastreabilidade em uma única visão.</p></div><div className="flex flex-wrap gap-2 print:hidden"><button onClick={()=>void loadManagement()} className="px-3 py-2 bg-white/10 rounded-lg text-xs font-bold flex items-center gap-1"><RefreshCw className={`w-4 h-4 ${loadingManagement?'animate-spin':''}`}/>Atualizar</button><button onClick={exportCsv} className="px-3 py-2 bg-white/10 rounded-lg text-xs font-bold flex gap-1"><Download className="w-4 h-4"/>CSV</button><button onClick={exportXlsx} className="px-3 py-2 bg-white/10 rounded-lg text-xs font-bold flex gap-1"><FileSpreadsheet className="w-4 h-4"/>Excel</button><button onClick={()=>window.print()} className="px-3 py-2 bg-[#FF8500] rounded-lg text-xs font-bold flex gap-1"><Printer className="w-4 h-4"/>PDF</button></div></div></section>
  {managementError&&<div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-800">A visão gerencial complementar não carregou: {managementError}. Os dados principais do SAC permanecem disponíveis.</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">{[['SACs',metrics.total,<TrendingUp/>],['Em andamento',metrics.open,<Clock/>],['Críticos',metrics.critical,<AlertTriangle/>],['SLA vencido',metrics.overdue,<Clock/>],['Pendências abertas',command.actions,<ClipboardList/>],['Pendências vencidas',command.overdueActions,<AlertTriangle/>],['Custo líquido',money.format(command.net),<WalletCards/>],['Tempo médio',`${metrics.averageDays.toFixed(1)} d`,<CheckCircle2/>]].map(([l,v,i])=><article key={String(l)} className="bg-white p-4 rounded-xl border shadow-sm"><div className="flex justify-between text-slate-500"><span className="text-[9px] uppercase font-black">{l}</span><span className="w-4 h-4">{i as React.ReactNode}</span></div><strong className="text-xl text-[#10233F]">{v}</strong></article>)}</div>
  <section className="bg-white p-5 rounded-2xl border shadow-sm"><div className="flex flex-wrap gap-2 text-xs print:hidden"><Filter className="w-4 h-4 mt-2 text-[#145EDB]"/><select value={period} onChange={e=>setPeriod(e.target.value as any)} className="border rounded-lg p-2"><option value="ALL">Todo histórico</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="365">12 meses</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg p-2"><option value="ALL">Todos status</option>{[...new Set(tickets.map(t=>t.status))].sort().map(v=><option key={v}>{v}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="border rounded-lg p-2"><option value="ALL">Todas prioridades</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="border rounded-lg p-2"><option value="ALL">Todas categorias</option>{categories.map(v=><option key={v}>{v}</option>)}</select><input value={productQuery} onChange={e=>setProductQuery(e.target.value)} placeholder="Produto, modelo, SKU, lote ou série" className="border rounded-lg p-2 min-w-64"/></div></section>
  <section className="bg-white p-5 rounded-2xl border shadow-sm"><h2 className="font-black text-[#10233F] mb-3">Ação prioritária</h2>{command.next.length===0?<p className="text-xs text-emerald-700">Nenhuma próxima ação com prazo registrada.</p>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Protocolo</th><th className="p-2 text-left">Cliente</th><th className="p-2 text-left">Responsável</th><th className="p-2 text-left">Pendências</th><th className="p-2 text-left">Próximo prazo</th><th className="p-2 text-right">Custo líquido</th></tr></thead><tbody>{command.next.map(r=>{const late=!!r.next_due_at&&new Date(r.next_due_at)<new Date();return <tr key={r.ticket_id} className={`border-t ${late?'bg-red-50':''}`}><td className="p-2 font-mono font-black text-[#145EDB]">{r.protocol}</td><td className="p-2">{r.customer_name}</td><td className="p-2">{r.assigned_to_name||r.assigned_area||'Não atribuído'}</td><td className="p-2">{r.open_actions}{r.overdue_actions>0&&<span className="ml-2 text-red-700 font-black">({r.overdue_actions} vencida(s))</span>}</td><td className={`p-2 ${late?'text-red-700 font-black':''}`}>{r.next_due_at?new Date(r.next_due_at).toLocaleString('pt-BR'):'-'}</td><td className="p-2 text-right font-bold">{money.format(r.net_cost)}</td></tr>})}</tbody></table></div>}</section>
  <section className="bg-white p-5 rounded-2xl border shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-black text-[#10233F] flex gap-2"><PackageSearch className="w-5 h-5 text-[#145EDB]"/>Qualidade do produto</h2><p className="text-xs text-slate-500">Dados necessários para histórico, laudos, relatórios e rastreabilidade.</p></div><span className={`text-xs font-black px-3 py-1 rounded-full ${quality.incomplete.length?'bg-amber-100 text-amber-800':'bg-emerald-100 text-emerald-800'}`}>{quality.incomplete.length} pendência(s)</span></div><div className="grid md:grid-cols-3 gap-3 mt-4">{[['Descrição completa',quality.description],['Modelo',quality.model],['Lote ou série',quality.trace]].map(([l,v])=><div key={String(l)} className="p-4 bg-slate-50 border rounded-xl"><p className="text-xs font-bold">{l}</p><strong className="text-2xl">{Number(v).toFixed(1)}%</strong></div>)}</div></section>
  <div className="grid lg:grid-cols-3 gap-4"><Ranking title="Categorias com maior volume" rows={topCategories}/><Ranking title="Produtos/modelos mais envolvidos" rows={topProducts}/><Ranking title="Clientes recorrentes" rows={recurring}/></div>
  <section className="bg-white p-5 rounded-2xl border shadow-sm"><h2 className="font-black text-[#10233F] mb-3">Base analítica dos protocolos</h2><div className="overflow-x-auto max-h-[520px]"><table className="w-full text-xs"><thead className="bg-slate-50 sticky top-0"><tr><th className="p-2 text-left">Protocolo</th><th className="p-2 text-left">Abertura</th><th className="p-2 text-left">Cliente</th><th className="p-2 text-left">Categoria</th><th className="p-2 text-left">Produto / descrição / modelo</th><th className="p-2 text-left">Lote / série</th><th className="p-2 text-left">Status</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-t align-top"><td className="p-2 font-mono font-black text-[#145EDB]">{t.protocol}</td><td className="p-2">{new Date(t.createdAt).toLocaleDateString('pt-BR')}</td><td className="p-2">{t.customerName}</td><td className="p-2">{t.category}</td><td className="p-2">{(t.items||[]).map(i=><div key={i.id}><b>{i.productName}</b>{i.productModel&&` · ${i.productModel}`}{i.productDescription&&<p className="text-slate-500 max-w-xl">{i.productDescription}</p>}</div>)}</td><td className="p-2">{(t.items||[]).map(i=><div key={i.id}>{i.lotNumber||i.serialNumber||'-'}</div>)}</td><td className="p-2 font-semibold">{t.status}</td></tr>)}</tbody></table></div></section>
 </div>
};
const Ranking:React.FC<{title:string;rows:Array<[string,number]>}>=({title,rows})=><section className="bg-white p-5 rounded-2xl border shadow-sm"><h3 className="font-black text-[#10233F] mb-3">{title}</h3>{rows.length===0?<p className="text-xs text-slate-500">Sem dados.</p>:<div className="space-y-2">{rows.map(([name,count],idx)=><div key={name} className="flex gap-3 items-center"><span className="w-6 text-xs font-black text-slate-400">{idx+1}.</span><div className="flex-1 min-w-0"><p className="text-xs font-semibold truncate">{name}</p><div className="h-1.5 bg-slate-100 rounded-full mt-1"><div className="h-full bg-[#145EDB] rounded-full" style={{width:`${Math.min(100,count/Math.max(1,rows[0][1])*100)}%`}}/></div></div><b>{count}</b></div>)}</div>}</section>;
