create table if not exists public.commercial_subscription_actions(
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  subscription_id uuid not null references public.tenant_subscriptions(id) on delete restrict,
  actor_id uuid not null references auth.users(id) on delete restrict,
  action text not null check(action in('BLOCK','UNBLOCK','CANCEL','REACTIVATE')),
  previous_status text not null,
  new_status text not null,
  reason text not null check(char_length(reason) between 10 and 1000),
  created_at timestamptz not null default now()
);
alter table public.commercial_subscription_actions enable row level security;
alter table public.commercial_subscription_actions force row level security;
revoke all on public.commercial_subscription_actions from anon,authenticated;
comment on table public.commercial_subscription_actions is 'Trilha imutável das decisões administrativas sobre acesso e assinatura.';

create or replace function public.prevent_subscription_action_mutation() returns trigger
language plpgsql set search_path=pg_catalog,public as $$ begin raise exception 'Ações de assinatura são imutáveis.'; end $$;
revoke all on function public.prevent_subscription_action_mutation() from public,anon,authenticated;
create trigger trg_subscription_actions_immutable before update or delete on public.commercial_subscription_actions
for each row execute function public.prevent_subscription_action_mutation();

create or replace function public.manage_commercial_subscription(p_subscription_id uuid,p_actor_id uuid,p_new_status text,p_reason text)
returns void language plpgsql security definer set search_path=pg_catalog,public set row_security=off as $$
declare current_row public.tenant_subscriptions%rowtype; action_name text;
begin
  select * into current_row from public.tenant_subscriptions where id=p_subscription_id for update;
  if current_row.id is null then raise exception 'Assinatura não encontrada.'; end if;
  if p_new_status not in('ACTIVE','SUSPENDED','CANCELED') then raise exception 'Status inválido.'; end if;
  if char_length(trim(coalesce(p_reason,'')))<10 then raise exception 'Justificativa obrigatória.'; end if;
  if current_row.status=p_new_status then raise exception 'Assinatura já está nesse status.'; end if;
  action_name:=case p_new_status when 'SUSPENDED' then 'BLOCK' when 'CANCELED' then 'CANCEL' when 'ACTIVE' then case when current_row.status='SUSPENDED' then 'UNBLOCK' else 'REACTIVATE' end end;
  update public.tenant_subscriptions set status=p_new_status,updated_at=now() where id=current_row.id;
  insert into public.commercial_subscription_actions(tenant_id,subscription_id,actor_id,action,previous_status,new_status,reason)
  values(current_row.tenant_id,current_row.id,p_actor_id,action_name,current_row.status,p_new_status,trim(p_reason));
end $$;
revoke all on function public.manage_commercial_subscription(uuid,uuid,text,text) from public,anon,authenticated;
grant execute on function public.manage_commercial_subscription(uuid,uuid,text,text) to service_role;
