create table if not exists public.ticket_actions (
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null, ticket_id uuid not null references public.tickets(id) on delete cascade,
 title text not null, description text, status text not null default 'OPEN' check(status in ('OPEN','IN_PROGRESS','DONE','CANCELLED')),
 priority text not null default 'MEDIUM' check(priority in ('LOW','MEDIUM','HIGH','CRITICAL')),
 responsible_id uuid, responsible_name text, due_at timestamptz, completed_at timestamptz, completion_notes text,
 source_event_id uuid references public.ticket_events(id) on delete set null, created_by uuid, created_by_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.ticket_actions enable row level security;
drop policy if exists ticket_actions_tenant_read on public.ticket_actions;
create policy ticket_actions_tenant_read on public.ticket_actions for select using (tenant_id=user_tenant_id());
drop policy if exists ticket_actions_tenant_write on public.ticket_actions;
create policy ticket_actions_tenant_write on public.ticket_actions for all using (tenant_id=user_tenant_id() and user_role_code()=any(array['SUPERADMIN','ADMIN_EMPRESA','DIRETORIA','RESPONSAVEL_TECNICA','SAC','TECNICO'])) with check (tenant_id=user_tenant_id() and user_role_code()=any(array['SUPERADMIN','ADMIN_EMPRESA','DIRETORIA','RESPONSAVEL_TECNICA','SAC','TECNICO']));
create index if not exists idx_ticket_actions_ticket_status_due on public.ticket_actions(ticket_id,status,due_at);
create or replace function public.log_ticket_action_event() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.ticket_events(tenant_id,ticket_id,event_type,title,description,actor_id,actor_name,source_type,source_id,metadata,occurred_at) values(new.tenant_id,new.ticket_id,case when tg_op='INSERT' then 'ACTION_CREATED' when new.status='DONE' and old.status is distinct from 'DONE' then 'ACTION_COMPLETED' else 'ACTION_UPDATED' end,case when tg_op='INSERT' then 'Pendência criada: '||new.title when new.status='DONE' and old.status is distinct from 'DONE' then 'Pendência concluída: '||new.title else 'Pendência atualizada: '||new.title end,coalesce(new.completion_notes,new.description),new.created_by,new.created_by_name,'ACTION',new.id,jsonb_build_object('status',new.status,'priority',new.priority,'responsible_name',new.responsible_name,'due_at',new.due_at,'completed_at',new.completed_at),now()); return new; end $$;
drop trigger if exists trg_ticket_action_event on public.ticket_actions;
create trigger trg_ticket_action_event after insert or update on public.ticket_actions for each row execute function public.log_ticket_action_event();
create or replace function public.complete_ticket_action(p_action_id uuid,p_notes text default null) returns void language plpgsql security definer set search_path=public as $$ declare a public.ticket_actions%rowtype; u public.profiles%rowtype; begin select * into u from public.profiles where id=auth.uid(); select * into a from public.ticket_actions where id=p_action_id and tenant_id=u.tenant_id; if not found then raise exception 'Pendência não encontrada.'; end if; update public.ticket_actions set status='DONE',completed_at=now(),completion_notes=nullif(trim(p_notes),''),created_by=u.id,created_by_name=u.full_name,updated_at=now() where id=p_action_id; end $$;
revoke all on function public.complete_ticket_action(uuid,text) from public; grant execute on function public.complete_ticket_action(uuid,text) to authenticated;
create or replace view public.sac_action_summary with (security_invoker=true) as select tenant_id,ticket_id,count(*) filter(where status not in ('DONE','CANCELLED'))::int open_actions,count(*) filter(where status not in ('DONE','CANCELLED') and due_at<now())::int overdue_actions,min(due_at) filter(where status not in ('DONE','CANCELLED')) next_due_at from public.ticket_actions group by tenant_id,ticket_id;