-- Console da plataforma: trilha imutável e correção de privilégios de clientes.

create table if not exists public.platform_admin_actions (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid references auth.users(id) on delete set null,
  tenant_id uuid references public.tenants(id) on delete set null,
  action text not null check (char_length(action) between 3 and 80),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_platform_admin_actions_created
  on public.platform_admin_actions(created_at desc);
create index if not exists idx_platform_admin_actions_tenant
  on public.platform_admin_actions(tenant_id,created_at desc);

alter table public.platform_admin_actions enable row level security;
alter table public.platform_admin_actions force row level security;
revoke all on public.platform_admin_actions from public,anon,authenticated;

create or replace function public.prevent_platform_admin_action_mutation() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
  raise exception 'A trilha administrativa é imutável.';
end $$;
revoke all on function public.prevent_platform_admin_action_mutation() from public,anon,authenticated;

drop trigger if exists trg_platform_admin_actions_immutable on public.platform_admin_actions;
create trigger trg_platform_admin_actions_immutable
before update or delete on public.platform_admin_actions
for each row execute function public.prevent_platform_admin_action_mutation();

-- Administradores de empresas clientes nunca devem possuir o papel global da GRIT.
update public.profiles p
set role_code='ADMIN_EMPRESA'
where p.role_code='SUPERADMIN'
  and exists (
    select 1 from public.commercial_trial_requests r
    where r.provisioned_admin_id=p.id and r.provisioned_tenant_id=p.tenant_id
  );

comment on table public.platform_admin_actions is
  'Trilha imutável das ações do superadministrador GRIT sobre empresas e usuários.';
