alter table public.commercial_orders drop constraint if exists commercial_orders_status_check;
alter table public.commercial_orders add constraint commercial_orders_status_check
  check (status in ('APPROVED','PAYMENT_PENDING','PAYMENT_REVIEW','PAID','REFUNDED','CHARGEBACK','CANCELED'));
alter table public.commercial_orders
  add column if not exists last_payment_status text,
  add column if not exists amount_refunded numeric(12,2) not null default 0 check (amount_refunded>=0);

create table if not exists public.commercial_billing_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.commercial_orders(id) on delete set null,
  provider text not null default 'mercado_pago',
  provider_payment_id text not null,
  event_status text not null,
  status_detail text not null default '',
  amount numeric(12,2),
  amount_refunded numeric(12,2) not null default 0,
  currency text,
  occurred_at timestamptz,
  received_at timestamptz not null default now(),
  unique(provider,provider_payment_id,event_status,status_detail,amount_refunded)
);

create table if not exists public.commercial_alerts (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.commercial_orders(id) on delete cascade,
  dedupe_key text not null unique,
  severity text not null check (severity in ('INFO','WARNING','CRITICAL')),
  alert_type text not null,
  message text not null,
  status text not null default 'OPEN' check (status in ('OPEN','ACKNOWLEDGED','RESOLVED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists idx_billing_events_order on public.commercial_billing_events(order_id,received_at desc);
create index if not exists idx_commercial_alerts_open on public.commercial_alerts(status,severity,created_at desc);

alter table public.commercial_billing_events enable row level security;
alter table public.commercial_billing_events force row level security;
alter table public.commercial_alerts enable row level security;
alter table public.commercial_alerts force row level security;
revoke all on public.commercial_billing_events,public.commercial_alerts from anon,authenticated;

create or replace function public.prevent_billing_event_mutation() returns trigger
language plpgsql set search_path=pg_catalog,public as $$ begin raise exception 'Eventos financeiros são imutáveis.'; end $$;
revoke all on function public.prevent_billing_event_mutation() from public,anon,authenticated;
drop trigger if exists trg_billing_events_immutable on public.commercial_billing_events;
create trigger trg_billing_events_immutable before update or delete on public.commercial_billing_events
for each row execute function public.prevent_billing_event_mutation();

comment on table public.commercial_billing_events is 'Livro imutável e idempotente dos estados financeiros recebidos do provedor.';
comment on table public.commercial_alerts is 'Alertas comerciais e financeiros deduplicados para tratamento operacional.';
