import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, BellRing, ClipboardCheck, FileCheck2, Plus, ShieldCheck, UploadCloud } from 'lucide-react';
import { Product, Tenant, Ticket, UserProfile } from '../../types';
import { RiskAction, RiskCase, SalesRecord, SamplingPlan, riskService } from '../../services/riskService';

type Tab = 'executive' | 'register' | 'notifications' | 'capa' | 'sales' | 'sampling' | 'audit';
const level = (score: number) => score >= 15 ? 'CRÍTICO' : score >= 8 ? 'ALTO' : score >= 4 ? 'MODERADO' : 'BAIXO';
const badge = (score: number) => score >= 15 ? 'bg-red-100 text-red-700' : score >= 8 ? 'bg-orange-100 text-orange-700' : score >= 4 ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700';
const isoDate = () => new Date().toISOString().slice(0, 10);

export const RiskManagement: React.FC<{ tenant: Tenant; currentUser: UserProfile; tickets: Ticket[]; products: Product[] }> = ({ tenant, currentUser, tickets, products }) => {
  const [tab, setTab] = useState<Tab>('executive');
  const [risks, setRisks] = useState<RiskCase[]>([]); const [actions, setActions] = useState<RiskAction[]>([]);
  const [sales, setSales] = useState<SalesRecord[]>([]); const [samples, setSamples] = useState<SamplingPlan[]>([]);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const canEdit = ['SUPERADMIN', 'RESPONSAVEL_TECNICA'].includes(currentUser.roleCode);
  const reload = async () => { try { setError(''); const data = await riskService.load(tenant.id); setRisks(data.risks); setActions(data.actions); setSales(data.sales); setSamples(data.samples); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar riscos.'); } };
  useEffect(() => { void reload(); }, [tenant.id]);

  const metrics = useMemo(() => {
    const sold = sales.reduce((n, r) => n + Number(r.units_sold || 0), 0);
    const overdue = actions.filter(a => !['DONE','CANCELLED'].includes(a.status) && a.when_due < isoDate()).length;
    return { critical: risks.filter(r => r.residual_score >= 15 && r.status !== 'CLOSED').length, notify: risks.filter(r => r.regulatory_notification_required && !['SUBMITTED','ACKNOWLEDGED','CLOSED'].includes(r.notification_status)).length, overdue, recurrence: risks.filter(r => r.recurrence_count > 0).length, sold, ppm: sold ? Math.round((tickets.length / sold) * 1_000_000) : 0 };
  }, [risks, actions, sales, tickets.length]);
  const signals = useMemo(() => {
    const list: string[] = [];
    if (metrics.critical) list.push(`${metrics.critical} risco(s) residual(is) crítico(s) exigem decisão e evidência da RT.`);
    if (metrics.notify) list.push(`${metrics.notify} avaliação(ões) regulatória(s) sem submissão registrada.`);
    if (metrics.overdue) list.push(`${metrics.overdue} ação(ões) CAPA vencida(s), com risco de recorrência e apontamento em auditoria.`);
    const recurring = [...risks].sort((a,b) => b.recurrence_count-a.recurrence_count)[0]; if (recurring?.recurrence_count) list.push(`Maior recorrência: ${recurring.code} — ${recurring.title} (${recurring.recurrence_count}).`);
    if (!metrics.sold) list.push('Importe vendas para calcular taxa de ocorrências por milhão de unidades e comparar produtos/lotes.');
    return list;
  }, [metrics, risks]);

  const createRisk = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!canEdit) return; const f = new FormData(event.currentTarget); setBusy(true); try {
    await riskService.createRisk({ tenant_id: tenant.id, code: `RIS-${Date.now().toString().slice(-8)}`, source: f.get('source'), title: f.get('title'), product_id: f.get('product_id') || null, lot_number: f.get('lot_number') || null, hazard: f.get('hazard'), hazardous_situation: f.get('situation'), harm: f.get('harm'), severity: Number(f.get('severity')), probability: Number(f.get('probability')), detectability: Number(f.get('detectability')), controls: f.get('controls'), residual_severity: Number(f.get('residual_severity')), residual_probability: Number(f.get('residual_probability')), regulatory_notification_required: f.get('notify') === 'on', notification_authority: f.get('authority') || null, notification_status: f.get('notify') === 'on' ? 'UNDER_REVIEW' : 'NOT_APPLICABLE', owner_id: currentUser.id, owner_name: currentUser.fullName, created_by: currentUser.id, predictive_signal: 'Apoio à decisão: correlacionar recorrência, severidade, lote e exposição de vendas; validação obrigatória pela RT.' });
    event.currentTarget.reset(); setNotice('Risco registrado com trilha de responsabilidade.'); await reload(); setTab('register');
  } catch(e) { setError(e instanceof Error ? e.message : 'Falha ao registrar.'); } finally { setBusy(false); } };

  const createAction = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); try { await riskService.createAction({ tenant_id: tenant.id, risk_case_id: f.get('risk'), action_type: f.get('type'), root_cause_method: '5 Porquês / Ishikawa', root_cause: f.get('cause'), what_action: f.get('what'), why_action: f.get('why'), where_action: f.get('where'), when_due: f.get('when'), who_name: f.get('who'), how_action: f.get('how'), how_much: Number(f.get('cost') || 0), effectiveness_criterion: f.get('criterion'), created_by: currentUser.id }); event.currentTarget.reset(); setNotice('Plano 5W2H criado. A eficácia deverá ser comprovada antes do encerramento.'); await reload(); } catch(e) { setError(e instanceof Error ? e.message : 'Falha ao criar 5W2H.'); } finally { setBusy(false); } };

  const importCsv = async (file?: File) => { if (!file) return; setBusy(true); try { const lines = (await file.text()).replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); const headers = lines.shift()!.split(/[;,]/).map(v => v.trim().toLowerCase()); const batch = crypto.randomUUID(); const rows = lines.map(line => { const values=line.split(/[;,]/).map(v=>v.trim()); const get=(name:string)=>values[headers.indexOf(name)]||''; return { tenant_id:tenant.id, import_batch:batch, period_start:get('period_start'), period_end:get('period_end'), sku:get('sku'), product_name:get('product_name'), lot_number:get('lot_number')||null, units_sold:Number(get('units_sold')), customers_count:Number(get('customers_count')||0), revenue:Number(String(get('revenue')||0).replace(',','.')), source_file:file.name, created_by:currentUser.id }; }); if (!rows.length || rows.some(r=>!r.period_start||!r.period_end||!r.sku||!r.product_name||!Number.isFinite(r.units_sold))) throw new Error('CSV inválido. Use o modelo indicado.'); await riskService.importSales(rows); setNotice(`${rows.length} linha(s) de vendas importada(s).`); await reload(); } catch(e) { setError(e instanceof Error ? e.message : 'Falha na importação.'); } finally { setBusy(false); } };

  const createSample = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget); const population=Number(f.get('population')); const sample=Number(f.get('sample')); setBusy(true); try { await riskService.createSample({ tenant_id:tenant.id, code:`AMP-${Date.now().toString().slice(-8)}`, audit_type:f.get('audit_type'), scope:f.get('scope'), population_size:population, sampling_method:f.get('method'), sample_size:sample, acceptance_number:Number(f.get('acceptance')), rejection_number:Number(f.get('rejection')), rationale:f.get('rationale'), audit_date:f.get('date')||null, created_by:currentUser.id }); setNotice('Plano de amostragem salvo para aprovação formal.'); await reload(); } catch(e) { setError(e instanceof Error ? e.message : 'Falha ao salvar amostragem.'); } finally { setBusy(false); } };

  const saveAudit = async () => { setBusy(true); try { await riskService.saveSnapshot({ tenant_id:tenant.id, report_type:'OCP', period_start:new Date(new Date().setFullYear(new Date().getFullYear()-1)).toISOString().slice(0,10), period_end:isoDate(), title:`Dossiê OCP — ${tenant.name}`, summary:{generated_at:new Date().toISOString(), metrics, signals, risks, actions, samples, sales_volume:metrics.sold}, created_by:currentUser.id }); setNotice('Dossiê congelado como evidência de auditoria.'); } catch(e) { setError(e instanceof Error ? e.message : 'Falha ao gerar evidência.'); } finally { setBusy(false); } };

  const cards = [{label:'Risco residual crítico',value:metrics.critical,icon:AlertTriangle},{label:'Notificações em análise',value:metrics.notify,icon:BellRing},{label:'CAPA vencidas',value:metrics.overdue,icon:ClipboardCheck},{label:'Ocorrências / milhão',value:metrics.ppm||'—',icon:BarChart3}];
  const tabs: [Tab,string][] = [['executive','Visão executiva'],['register','Mapa de riscos'],['notifications','Notificações'],['capa','CAPA / 5W2H'],['sales','Vendas × problemas'],['sampling','Amostragem'],['audit','Dossiê OCP']];
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-[#10233F] flex items-center gap-2"><ShieldCheck className="text-[#145EDB]"/>Gestão de Riscos & Conformidade</h1><p className="text-sm text-slate-500">Risco → controle → CAPA → eficácia → notificação → auditoria</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{currentUser.roleCode.replaceAll('_',' ')}</span></div>
    {(error||notice) && <div className={`rounded-xl border p-3 text-sm ${error?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{error||notice}</div>}
    <div className="flex gap-2 overflow-x-auto border-b">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap px-3 py-2 text-xs font-bold ${tab===id?'border-b-2 border-[#145EDB] text-[#145EDB]':'text-slate-500'}`}>{label}</button>)}</div>

    {tab==='executive' && <><div className="grid gap-3 md:grid-cols-4">{cards.map(c=><div key={c.label} className="rounded-xl border bg-white p-4 shadow-sm"><c.icon className="mb-3 h-5 w-5 text-[#FF8500]"/><p className="text-2xl font-black text-[#10233F]">{c.value}</p><p className="text-xs text-slate-500">{c.label}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="font-bold text-[#10233F]">Sinais preditivos para validação da RT</h2><p className="mb-3 text-xs text-slate-500">Priorização baseada nos dados cadastrados; não substitui investigação ou decisão regulatória.</p><div className="space-y-2">{signals.map((s,i)=><div key={i} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{s}</div>)}</div></section><section className="rounded-xl border bg-white p-5"><h2 className="font-bold text-[#10233F]">Governança executiva</h2><div className="mt-3 grid grid-cols-2 gap-3 text-center"><div className="rounded-lg bg-slate-50 p-3"><b className="text-xl">{risks.length}</b><p className="text-xs">riscos registrados</p></div><div className="rounded-lg bg-slate-50 p-3"><b className="text-xl">{metrics.sold.toLocaleString('pt-BR')}</b><p className="text-xs">unidades vendidas</p></div><div className="rounded-lg bg-slate-50 p-3"><b className="text-xl">{samples.length}</b><p className="text-xs">planos de amostragem</p></div><div className="rounded-lg bg-slate-50 p-3"><b className="text-xl">{actions.length}</b><p className="text-xs">ações CAPA</p></div></div></section></div></>}

    {tab==='register' && <div className="grid gap-5 xl:grid-cols-[1fr_1.35fr]">{canEdit&&<form onSubmit={createRisk} className="rounded-xl border bg-white p-5 space-y-3"><h2 className="font-bold">Nova análise de risco</h2><div className="grid grid-cols-2 gap-2"><select name="source" className="input" required><option>SAC</option><option>AUDITORIA</option><option>TECNOVIGILANCIA</option><option>POS_MERCADO</option></select><select name="product_id" className="input"><option value="">Produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.codeSku} — {p.name}</option>)}</select></div>{['title','lot_number','hazard','situation','harm','controls'].map((n,i)=><input key={n} name={n} required={![1,3,5].includes(i)} className="input" placeholder={['Título do risco','Lote (opcional)','Perigo identificado','Situação perigosa','Dano possível','Controles existentes/propostos'][i]}/>)}<div className="grid grid-cols-3 gap-2">{[['severity','Severidade'],['probability','Probabilidade'],['detectability','Detecção'],['residual_severity','Sev. residual'],['residual_probability','Prob. residual']].map(([n,l])=><label key={n} className="text-[10px] text-slate-500">{l}<select name={n} defaultValue="3" className="input mt-1">{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label>)}</div><div className="flex gap-3"><label className="text-xs"><input type="checkbox" name="notify"/> Requer avaliação de notificação</label><select name="authority" className="input"><option value="">Autoridade</option><option>ANVISA</option><option>INMETRO</option><option>OCP</option></select></div><button disabled={busy} className="btn-primary w-full"><Plus className="h-4 w-4"/>Registrar e avaliar</button></form>}<section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Registro mestre</h2><div className="mt-3 space-y-2">{risks.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><b>{r.code} · {r.title}</b><p className="text-xs text-slate-500">{r.hazard} → {r.harm}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-bold ${badge(r.residual_score)}`}>{level(r.residual_score)} · {r.residual_score}</span></div><p className="mt-2 text-[11px] text-slate-500">Responsável: {r.owner_name||'não definido'} · Eficácia: {r.effectiveness_status}</p></div>)}{!risks.length&&<p className="text-sm text-slate-400">Nenhum risco registrado.</p>}</div></section></div>}

    {tab==='notifications' && <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Controle de notificações e ações de campo</h2><p className="text-xs text-slate-500">A RT documenta aplicabilidade, prazo, protocolo, comunicação aos clientes e encerramento.</p><div className="mt-4 space-y-2">{risks.filter(r=>r.regulatory_notification_required).map(r=><div key={r.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-4"><b>{r.code}</b><span>{r.notification_authority||'Em avaliação'}</span><span>{r.notification_status}</span><span>Prazo: {r.notification_deadline||'a definir pela RT'}</span></div>)}</div></section>}

    {tab==='capa' && <div className="grid gap-5 lg:grid-cols-2">{canEdit&&<form onSubmit={createAction} className="rounded-xl border bg-white p-5 space-y-3"><h2 className="font-bold">Plano CAPA — 5W2H</h2><select name="risk" required className="input"><option value="">Selecione o risco</option>{risks.map(r=><option key={r.id} value={r.id}>{r.code} — {r.title}</option>)}</select><select name="type" className="input"><option value="CORRECTIVE">Ação corretiva</option><option value="PREVENTIVE">Ação preventiva</option><option value="CONTAINMENT">Contenção</option><option value="CORRECTION">Correção imediata</option></select>{[['cause','Causa raiz comprovada'],['what','O quê será feito?'],['why','Por quê?'],['where','Onde?'],['who','Quem?'],['how','Como?'],['criterion','Critério mensurável de eficácia']].map(([n,p])=><input key={n} name={n} required={n!=='where'} className="input" placeholder={p}/>)}<div className="grid grid-cols-2 gap-2"><input name="when" type="date" required className="input"/><input name="cost" type="number" min="0" step="0.01" className="input" placeholder="Quanto custa?"/></div><button className="btn-primary w-full">Criar 5W2H</button><p className="text-[11px] text-slate-500">Exemplo: segregar lote, confirmar causa em embalagem, revisar fornecedor, treinar recebimento e comprovar zero recorrência em 90 dias.</p></form>}<section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Ações e eficácia</h2><div className="mt-3 space-y-2">{actions.map(a=><div key={a.id} className="rounded-lg border p-3"><b>{a.action_type} · {a.what_action}</b><p className="text-xs">Responsável: {a.who_name} · prazo {a.when_due}</p><p className="text-xs text-slate-500">Eficácia: {a.effectiveness_criterion}</p></div>)}</div></section></div>}

    {tab==='sales' && <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Exposição de mercado × ocorrências</h2><p className="text-xs text-slate-500">CSV: period_start;period_end;sku;product_name;lot_number;units_sold;customers_count;revenue</p>{canEdit&&<label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#145EDB] px-4 py-2 text-sm font-bold text-white"><UploadCloud className="h-4 w-4"/>Importar relatório de vendas<input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>void importCsv(e.target.files?.[0])}/></label>}<div className="mt-5 overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th>Período</th><th>SKU / Produto</th><th>Lote</th><th>Unidades</th></tr></thead><tbody>{sales.map(s=><tr key={s.id} className="border-b"><td>{s.period_start} a {s.period_end}</td><td>{s.sku} · {s.product_name}</td><td>{s.lot_number||'—'}</td><td>{s.units_sold.toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div></section>}

    {tab==='sampling' && <div className="grid gap-5 lg:grid-cols-2">{canEdit&&<form onSubmit={createSample} className="rounded-xl border bg-white p-5 space-y-3"><h2 className="font-bold">Plano controlado de amostragem</h2><select name="audit_type" className="input"><option>OCP</option><option>INTERNAL</option><option>SUPPLIER</option><option>REGULATORY</option></select><input name="scope" required className="input" placeholder="Escopo, produto, lote ou processo"/><div className="grid grid-cols-3 gap-2"><input name="population" required type="number" min="1" className="input" placeholder="População"/><input name="sample" required type="number" min="1" className="input" placeholder="Amostra"/><input name="date" type="date" className="input"/></div><input name="method" required className="input" placeholder="Método / plano normativo aplicável"/><div className="grid grid-cols-2 gap-2"><input name="acceptance" required type="number" min="0" className="input" placeholder="Aceitação"/><input name="rejection" required type="number" min="1" className="input" placeholder="Rejeição"/></div><textarea name="rationale" required className="input" placeholder="Justificativa estatística, RAC/requisito e aprovação da RT/OCP"/><button className="btn-primary w-full">Salvar para aprovação</button><p className="text-[11px] text-amber-700">O sistema não inventa um plano: tamanho, Ac/Re e método devem seguir o RAC, norma ou procedimento aplicável.</p></form>}<section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Planos auditáveis</h2>{samples.map(s=><div key={s.id} className="mt-3 rounded-lg border p-3 text-xs"><b>{s.code} · {s.audit_type}</b><p>{s.scope}</p><p>População {s.population_size} · amostra {s.sample_size} · Ac {s.acceptance_number} / Re {s.rejection_number}</p><p className="text-slate-500">{s.rationale}</p></div>)}</section></div>}

    {tab==='audit' && <section className="rounded-xl border bg-white p-6 print:border-0"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">Dossiê para auditoria OCP</h2><p className="text-xs text-slate-500">{tenant.name} · emitido em {new Date().toLocaleString('pt-BR')}</p></div><div className="flex gap-2 print:hidden"><button onClick={()=>window.print()} className="btn-secondary">Imprimir / PDF</button>{canEdit&&<button onClick={saveAudit} className="btn-primary"><FileCheck2 className="h-4 w-4"/>Congelar evidência</button>}</div></div><div className="my-5 grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(c=><div className="rounded-lg bg-slate-50 p-3" key={c.label}><b className="text-lg">{c.value}</b><p className="text-[10px]">{c.label}</p></div>)}</div><h3 className="font-bold">Conteúdo verificável</h3><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm"><li>Registro de riscos com perigos, danos, estimativas inicial e residual.</li><li>Controles implementados, responsável, prazo e evidência de eficácia.</li><li>Notificações e ações de campo, protocolos e comunicações.</li><li>CAPA/5W2H, causa raiz e verificação de não recorrência.</li><li>Planos de amostragem aprovados e rastreabilidade da seleção.</li><li>Volume vendido, ocorrências e tendências por produto e lote.</li></ol></section>}
    <style>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.6rem;padding:.55rem .7rem;font-size:.78rem;background:white}.btn-primary,.btn-secondary{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;border-radius:.55rem;padding:.55rem .85rem;font-size:.75rem;font-weight:700}.btn-primary{background:#145EDB;color:white}.btn-secondary{border:1px solid #cbd5e1;color:#334155;background:white}`}</style>
  </div>;
};
